### ISSUE TITLE
ServiceManagerTicketReviewPolicy does not handle multi-point request failures properly

### ISSUE THREAD

**Issue by hinchliff** [RENCI-NRIG/orca5#103]
Earlier, I was able to submit a Multi-Point request to my emulation environment, and received the following reservations states:

> Resources reserved from Fri Feb 10 10:35:08 EST 2017 until Sat Feb 11 10:35:08 EST 2017
>  
> Node | State | Message | Management
> ---|---|----|---
> Node0 | Closed | Reservation 03b4cf5b-c449-47c4-81ec-162001dd76a9 (Slice mp) is in state [Closed,None], err=TicketReview: Closing reservation due to failure in Slice. | No management access
> Node1 | Active | Reservation b656a5a6-5dfd-4820-8d96-e0f3441989c5 (Slice mp) is in state [Active,None] | No management access
> Node2 | Closed | Reservation 1e2050aa-ff60-47e3-b1cc-4b6afd7c79d6 (Slice mp) is in state [Closed,None], err=TicketReview: Closing reservation due to failure in Slice. | No management access
> VLAN0 | Closed | Reservation a0be0d3f-3bd6-47a1-a222-64f86cb31a15 (Slice mp) is in state [Closed,None], err=TicketReview: Closing reservation due to failure in Slice. | No management access
> bbnNet/Domain/vlan/e048f612-fdb4-4e94-82b7-b6d52d7eb1e6/vlan | Active | Reservation db540e3c-0035-459d-9b97-150d28190347 (Slice mp) is in state [Active,None] | No management access
> ben/Domain/vlan/88c17bc1-7a93-47b9-a1ad-b973988f959a/vlan | Active | Reservation 51b1fc7c-908b-4127-8302-b95d28ad6dcc (Slice mp) is in state [Active,None] | No management access
> dukeNet/Domain/vlan/c3c44637-e542-4a07-b2b2-4d8e289d84f6/vlan | Active | Reservation 02a9cb50-88db-46dd-a13e-e61a5bbd26c4 (Slice mp) is in state [Active,None] | No management access
> fiuNet/Domain/vlan/eb893012-6db5-41c3-aea4-71a252e88723/vlan | Closed | Reservation f9c56140-5ae3-464e-84e6-9b37fbd174ca (Slice mp) is in state [Closed,None], err=TicketReview: Closing reservation due to failure in Slice. | No management access
> ion/Domain/vlan/6afcbf2d-9ac5-4a1f-9bb6-48afbc6094e5/vlan | Closed | Reservation b0d6eacc-c091-4982-bf02-b2f9d5ac1608 (Slice mp) is in state [Closed,None], err=TicketReview: Closing reservation due to failure in Slice. | No management access
> ion/Domain/vlan/ac7cbb13-3219-438e-8323-ddf526d20f78/vlan | Closed | Reservation 0d7be8d2-8884-4265-899e-35ca989726df (Slice mp) is in state [Closed,None], err=TicketReview: Closing reservation due to failure in Slice. Last lease update: all units failed priming: Exception during join for unit: 826DF0C9 An error occurred mapping urn: ${oscars.site.properties} (No such file or directory) | No management access

The TicketReview should have Closed all of the reservations after the one had failed.  It's not clear why it only Closed some of them.  Perhaps some of the reservations had not been added to the Slice when the TicketReview closed what was existing, and then more reservations were added to the slice later and were allowed to go Active?

Of course, I haven't been able to replay that request in emulation more recently, instead I get the following error in Flukes:

> Exception encountered while submitted slice request to ORCA:
Unable to create slice: ERROR: Embedding workflow ERROR: 1:There is no multicast capable domain!.

Strange.

**Comment by hinchliff** [comment]
The above error was the result of the [mp.rdf](https://github.com/RENCI-NRIG/orca5/blob/master/embed/src/test/resources/orca/embed/mp.rdf) request that I added to test resources.  It used three nodes at three different sites, with "Auto IP" configured.   I haven't been able to get my emulation environment to reproduce that failure mode, which is strange and probably concerning.

I did get a different error today, by doing the same request, but _without_ the "Auto IP" configured.  This resulted in the request never completing.  The initial createSlice() comes back from the Controller with no errors.  But Polling for the Manifest, the request never completes.  Only two of the sites are successful (in my example, RENCI and Duke), but the third site (FIU, with an ION vlan) never completes.  The Controller doesn't seem to know that it has failed somehow?

I didn't find much in the way of error messages in the logs either, but I did find this:

> 2017-02-15 15:03:41,940-[test-fiunet-site]-{ERROR}-orca.test-fiunet-site-(AuthorityCalendarPolicy.java:512)-Could not assign
java.lang.Exception: NdlInterfaceVLANControl.assign(): DomainResources is null, unable to proceed
        at orca.plugins.ben.control.NdlInterfaceVLANControl.assign(NdlInterfaceVLANControl.java:121)
        at orca.policy.core.AuthorityCalendarPolicy.assign(AuthorityCalendarPolicy.java:502)
        at orca.policy.core.AuthorityCalendarPolicy.map(AuthorityCalendarPolicy.java:472)
        at orca.policy.core.AuthorityCalendarPolicy.mapGrowing(AuthorityCalendarPolicy.java:455)
        at orca.policy.core.AuthorityCalendarPolicy.mapForCycle(AuthorityCalendarPolicy.java:392)
        at orca.policy.core.AuthorityCalendarPolicy.assign(AuthorityCalendarPolicy.java:361)
        at orca.shirako.core.Authority.tickHandler(Authority.java:366)
        at orca.shirako.core.Actor.actorTick(Actor.java:428)
        at orca.shirako.core.Actor.access$000(Actor.java:60)
        at orca.shirako.core.Actor$1.process(Actor.java:333)
        at orca.shirako.core.Actor.actorMain(Actor.java:377)
        at orca.shirako.core.Actor$4.run(Actor.java:1018)
        at java.lang.Thread.run(Thread.java:745)


This is what the request looks like when I do View as List:
> Resources reserved from Wed Feb 15 15:17:01 EST 2017 until Thu Feb 16 15:17:01 EST 2017
> 
> Node | State | Message | Management
> ---|---|----|---
> Node0 | Active  | Reservation 7625cc9c-0835-4868-bdec-25fae78b0844 (Slice 103mp) is in state [Active,None] | No management access
> Node1 | Active  | Reservation 49bfff09-49a1-4cde-ab11-a4b877fd7964 (Slice 103mp) is in state [Active,None] | No management access
> Node2 | Ticketed  | Reservation c6ce50ea-04dd-432b-8f50-4d42e86d2bcc (Slice 103mp) is in state [Ticketed,None] | No management access
> VLAN2 | Ticketed  | Reservation 3eeca9a4-58c7-48a6-9632-5117eec5d4ad (Slice 103mp) is in state [Ticketed,None] | No management access
> ben/Domain/vlan/3e95096a-24e5-4df1-98b2-141e70ff326f/vlan | Active  | Reservation 5cf10765-5a29-47f3-9cb7-d5ddfc227101 (Slice 103mp) is in state [Active,None] | No management access
> ben/Domain/vlan/a7ad7304-339e-40c1-9866-cc47e6bc3f74/vlan | Active  | Reservation 9d343a1b-544f-4eee-ad88-d64628e1713a (Slice 103mp) is in state [Active,None] | No management access
> dukeNet/Domain/vlan/fa462a9e-bc28-4452-b402-32dcbfd8e2bd/vlan | Active  | Reservation 4f65ac2f-9387-4fd8-9442-d4b3b322f5bf (Slice 103mp) is in state [Active,None] | No management access
> fiuNet/Domain/vlan/97c3f788-20ca-418f-9b6a-3240eb191516/vlan | Ticketed  | Reservation 45d27f5a-8c64-4793-9463-8f1d0991c8c2 (Slice 103mp) is in state [Ticketed,Redeeming] | No management access
> ion/Domain/vlan/522733c4-9220-4766-a694-7125cb76e86f/vlan | Ticketed  | Reservation 6cecb9d9-2d88-49b7-9741-072835c69833 (Slice 103mp) is in state [Ticketed,None] | No management access
> rciNet/Domain/vlan/9608a27b-fe65-4eba-bd32-79a6a7f2065a/vlan | Active  | Reservation 69667416-5535-45a5-b8f9-6582ce0484f0 (Slice 103mp) is in state [Active,None] | No management access

I do wonder if either / any of these errors are based on the configuration of my emulation environment, but I am not sure.

**Comment by YufengXin** [comment]
I think the reason is that FIU site is down, not even delegated?

-Yufeng

**Comment by YufengXin** [comment]
<end>2031-01-30T00:00:00</end>
                                        <handler path="oscars/handler.xml">
                                                <properties>
                                                        <property name="ion.credentials" value="/etc/orca/am+broker-12080/config/ion.cred.properties" />
                                                <property name="oscars.site.properties" value="/etc/orca/am+broker-12080/config/oscars.site.properties" />
                                                </properties>
                                        </handler>

**Comment by hinchliff** [comment]
Yufeng pointed out that the error "There is no multicast capable domain!" was probably because my emulation environment had not completely initialized all of the domains.  Waiting for a longer period after emulation startup has allowed me to replicate the [original](https://github.com/RENCI-NRIG/orca5/issues/103#issue-206875941) failure (which suggests a defect in TicketReview).

It very much seems that some of the slice reservations are making it from Ticketed → Active before other reservations are even being added to the slice.  (If you're quick, you can watch this when doing a Poll Manifest.)

**Comment by ibaldin** [comment]
Does this mean we may need to introduce a barrier in the controller to send all reservations at once? I believe it is correct to say that the reservations are being sent to SM (and broker) by the controller on the ongoing basis - there is no single ‘flag’ moment when all of them are sent in bulk, but perhaps that is what is required here?

**Comment by hinchliff** [comment]
Something like that is probably the most likely.

**Comment by ibaldin** [comment]
This will affect the performance and may make the communications channel between the actors (controller, SM, broker) a bottleneck. That said, I don’t know if we have any alternative ideas at this time.

-ilya

**Comment by hinchliff** [comment]
Actually, it looks like this ([at least the first case](https://github.com/RENCI-NRIG/orca5/issues/103#issue-206875941)) is not (necessarily) an error on the part of ServiceManagerTicketReviewPolicy.  The Ion reservation that fails only fails _after_ being Ticketed.  

TicketReview does correctly hold all of the tickets until they are all active.  But when the Ion reservation later fails, it starts failing/closing other the other reservations.  (This may or may not be what we intended to do.)


The [second main case](https://github.com/RENCI-NRIG/orca5/issues/103#issuecomment-280128759), is probably not a TicketReview error.  But may be an error that we need to examine.  I haven't yet looked into that one more to see what is going on.

**Comment by hinchliff** [comment]
When do reservations normally transition from Failed to Closed?

Right now there doesn't seem to be any way for me to tell, in TicketReview, what a reservations previous state was -- e.g. did it fail in between Nascent → Ticketed, or did it fail after Ticketed.  This by itself is maybe not too bad.

But if a reservation can stay in the Failed state, then I think the next time TicketReview is called on that slice (on potentially unrelated modifications in a separate request), TicketReview will Fail and Close all of those new reservations.

I didn't implement [recommendation 5.i.](https://github.com/RENCI-NRIG/orca5/issues/88#issuecomment-275449931) from the previous ticket, because I started Closing and not just Failing reservations.  But if other causes of reservation failure are going to leave Failed reservations lying around, this may become a problem.

**Comment by ibaldin** [comment]
Either the user closes the slice reservations explicitly or they close when the calendar tells them the term has expired. I think that's correct.

**Comment by hinchliff** [comment]
I guess requiring a user to close the reservation is not too terrible... ?

**Comment by ibaldin** [comment]
It all depends on how efficient we want to be. If there is a failure on the AM, broker doesn't know about it and the resource is counted as 'taken'. We discussed in the past whether we should automatically close those on the broker and decided against it (instead expecting the user to do it explicitly or just waiting it out)

**Comment by hinchliff** [comment]
The [second main case](https://github.com/RENCI-NRIG/orca5/issues/103#issuecomment-280128759) is just a configuration issue in my emulation environment.  I get the following message from the AM on startup:

>2017-02-16 20:02:53,442-[WrapperSimpleAppMain]-{ERROR}-ndl.logger-(Domain.java:306)-http://geni-orca.renci.org/owl/fiuNet.rdf#fiuNet/Domain/vlan:VLAN:Too many delegated units from the config.xml, total=20, than specified in the site RDF units=10, please modify and restart the actor!

This leaves the DomainResources `drs` null, causing the later exception in [AuthorityCalendarPolicy.assign()](https://github.com/RENCI-NRIG/orca5/blob/master/core/policy/src/main/java/orca/policy/core/AuthorityCalendarPolicy.java#L503)

Of course, I can't figure out where in my config.xml I'm specifying total=20 units, but that is a separate problem.  (I even changed what looked like the most likely number from 10 to 5, and I still get the same error.)

I think all of this means I can close this ticket.

**Comment by ibaldin** [comment]
Its a mismatch between rdf and config.xml
