### ISSUE TITLE
User specified VLAN tag causing VLAN to fail

### ISSUE THREAD

**Issue by hinchliff** [RENCI-NRIG/orca5#113]
There seems to be an error running regression test [TS2-8](https://github.com/RENCI-NRIG/orca5/blob/orca-5.1.3/embed/src/test/resources/orca/embed/TS2/TS2-8.rdf).

This is the test description from the README:
> Broadcast link with user specified vlan tag, 3 vms, rcivmsite.

In unit tests and in emulation, the VLAN seems to just get lost -- the response from the createSlice() from the Controller only provides leases for the VMs, and doesn't mention the VLAN:
```
Here are the leases: 
Request id: c69a87db-8524-4cbf-881d-19d1ac66e375
[   Slice UID: c69a87db-8524-4cbf-881d-19d1ac66e375 | Reservation UID: 8e71855a-a287-405d-8074-6c87c4bdd128 | Resource Type: ncsuvmsite.vm | Resource Units: 1 ] 
[   Slice UID: c69a87db-8524-4cbf-881d-19d1ac66e375 | Reservation UID: fe179975-6212-4d9e-b8fd-325dd311e474 | Resource Type: ncsuvmsite.vm | Resource Units: 1 ] 
[   Slice UID: c69a87db-8524-4cbf-881d-19d1ac66e375 | Reservation UID: 8b29e0bc-8c7c-4424-8fa6-999211e36ca7 | Resource Type: ncsuvmsite.vm | Resource Units: 1 ] 
```

Using ExoSM, the error is different:
> java.lang.Exception: Unable to create slice: ERROR: Embedding workflow ERROR: 1:Cannot create the network reservation, likely no available resource, the user specified label or hybrid OF is not valid in this site:http://geni-orca.renci.org/owl/pscvmsite.rdf#pscvmsite/Domain.

From stepping through the debugger in the unit test, it seems like the VLAN is being marked as non-Allocatable, and then never makes it into the list of reservations.

@YufengXin  Is there an error in the way that non-Allocatable reservations become allocated?  Is this something that can be tested in emulation? (It seems like the ExoSM is failing for a different reason.  Is that VLAN tag already in use?  Would it work in ExoSM with a different tag?)

**Comment by ibaldin** [comment]
@YufengXin should answer, but I think the behavior is mostly correct, i.e. a VLAN where you specfy a tag is assumed to be 'shared' and non-allocatable. I don't know where the error comes from.

**Comment by hinchliff** [comment]
Everything here is actually working correctly.  

1. The shared VLAN should not be given a reservation, so the emulation and unit test behavior was correct.
1. The request RDF does not actually specify the site, but the shared VLAN tag is dependent on the site.  When the request is given to the ExoSM with the correct site specified, the ExoSM also displays the correct behavior.
