### ISSUE TITLE
Regression tests as Unit tests

### ISSUE THREAD

**Issue by hinchliff** [RENCI-NRIG/orca5#114]
I've been working on getting the regressions tests in [embed](https://github.com/RENCI-NRIG/orca5/blob/master/embed/src/test/resources/orca/embed/README) working as [unit tests](https://github.com/RENCI-NRIG/orca5/blob/master/controllers/xmlrpc/src/test/java/orca/controllers/xmlrpc/OrcaRegressionTest.java), and most of them seem to be [working well](https://github.com/RENCI-NRIG/orca5/tree/regression_tests) enough now, but there a couple of issues.

1. Several of the tests were failing in unit tests with errors like `ERROR: 2:Path does NOT exist` when trying to setup Inter-Domain links (e.g. [TS3-3](https://github.com/RENCI-NRIG/orca5/blob/master/embed/src/test/resources/orca/embed/TS3/TS3-3.rdf)).  I was able to fix this by copying the substrate files from my emulation environment into the git source code (e.g. [ben-6509.rdf](https://github.com/RENCI-NRIG/orca5/blob/370e44e321a550b132316cf87b5ae3788a25f3c3/ndl/src/main/resources/orca/ndl/substrate/ben-6509.rdf)), but looking back, I don't think this was the right way to fix this (that's why it's in a branch! :)
   - Where should I be looking to get substrate files that work together?  Should I look at functional AM(s)?
1. Some of the tests still are not working in Unit Tests:
   - [TS5-1](https://github.com/RENCI-NRIG/orca5/blob/master/embed/src/test/resources/orca/embed/TS5/TS5-1.rdf) gives `ERROR: 2:Path does NOT exist` in the unit test.  In emulation, it works fine; but all nodes are placed at a single site.  In live tests, all nodes are again placed at a single site, but the ticketing fails because the image is not found.  I could probably fix the missing image problem, but I'm not sure exactly what this should be testing -- multiple sites? Should this unit test be able to pass?
   - [TS7-1](https://github.com/RENCI-NRIG/orca5/blob/master/embed/src/test/resources/orca/embed/TS7/TS7-1.rdf) gives the `ERROR: 2:Path does NOT exist` in both the unit test and in emulation.  I'm not sure about how to create stitchports in the live system.  Should this unit test be able to pass?
1. [TS3-13](https://github.com/RENCI-NRIG/orca5/blob/master/embed/src/test/resources/orca/embed/TS3/TS3-13.rdf) and [TS3-14](https://github.com/RENCI-NRIG/orca5/blob/master/embed/src/test/resources/orca/embed/TS3/TS3-14.rdf) both seem to work fine in the Unit test, but they fail in emulation with the `ERROR: 4:No Edge Domain Exist`.  So they probably shouldn't be passing in the unit tests?

**Comment by mcevik0** [comment]
I checked the request RDF files (TS3-3, TS3-13, TS3-14, TS5-1, TS7-1). They have requests for sites that do not exist (Duke, UNC BEN). I think they need to be reviewed and modified according to the current state of the active racks. Also, images should be checked if they exist or not and maybe replaced with the standard images. Some of the nodes/nodegroups have "System Select" setting. If they're intended to test inter-domain connections, then maybe domains should specifically selected. (I did not read the descriptions for the tests yet, maybe this is explained). So, if the requests are modified slightly, then I guess they will work.

**Comment by hinchliff** [comment]
Thank you Mert.

I updated a bunch of the test cases yesterday, most of them should be better now.  TS3-3 and TS3-13 now work correctly.  

However, I'm not sure if [TS3-14](https://github.com/RENCI-NRIG/orca5/blob/regression_tests/embed/src/test/resources/orca/embed/TS3/TS3-14.rdf) is working correctly from ExoSM. (The version in 'master' is outdated, so you will need to grab the version from my branch linked here.)

>3-14: Router node configuration TS3-12 with splittable groups

![ts3-14_request](https://cloud.githubusercontent.com/assets/10090677/24262767/7b9a5cb4-0fd1-11e7-9bf5-3ef4cb2a3a39.png)

This test is supposed is supposed to create 3 node groups, two with 48 VMs and a third with 2 VMs.  However ExoSM is only creating a total of about 55 reservations:
![ts3-14_polling](https://cloud.githubusercontent.com/assets/10090677/24262853/c8158b5e-0fd1-11e7-99c8-1681df2a5920.png)

The test seems to be working correctly in the regression tests, creating a total of 104 reservations. 

Of course, sometimes the ExoSM gives me the error `ERROR: 4:No Edge Domain Exist`.   Any idea why this doesn't seem to be working correctly?

**Comment by mcevik0** [comment]
I think available resources to ExoSM have an impact on this. 
- The request has "System Select" and "Splittable between domains" options for the nodegroups that have 48 VMs. 
- Not all of the racks have 48 VMs available for ExoSM.

First slice: I created a slice with one nodegroup connected to a VM.
Single VM: BBN rack selected.
Node Group: 21 VMs (to be safe if BBN was picked), "System select", "Splittable between domains"
All VMs were created on BBN rack.

Second slice: Request TS3-14, just number of VMs in the node groups decreased to 2. 
Slice created successfully.

Third slice: Request TS3-14, racks that have 48 VMs are selected instead of "System Select" (FIU and PSC at this time).
Slice created successfully.

I think it would be better to know which racks ExoSM picks (and fails) when "System Select" is used.

**Comment by hinchliff** [comment]
Yes, we probably shouldn't be silently failing here, when ExoSM picks (and fails) when "System Select" is used?  @YufengXin @ibaldin

**Comment by YufengXin** [comment]
Yes, I agree. It was underimplemented.

-Yufeng.
