### ISSUE TITLE
Connecting node to two stitchports (same or different) results in embedding error

### ISSUE THREAD

**Issue by ibaldin** [RENCI-NRIG/orca5#120]
Copied from RENCI-NRIG/exogeni#136:

I submitted the requests below and they both ended up with exceptions:
1. VM connected to two stitchports from the same domain with different VLAN tags
2. VM connected to two stitchports from different domains

```
1.   SP1 <===>  VM <===>  SP2
      SP1 - URL: http://geni-orca.renci.org/owl/ion.rdf#AL2S/Chameleon/Cisco/6509/GigabitEthernet/1/1
      SP1 - VLAN Tag: 3291
      SP2 - URL: http://geni-orca.renci.org/owl/ion.rdf#AL2S/Chameleon/Cisco/6509/GigabitEthernet/1/1
      SP2 - VLAN Tag: 3292
```

[request-stitchport-URLcham-TAG3291-3292.txt](https://github.com/RENCI-NRIG/exogeni/files/910656/request-stitchport-URLcham-TAG3291-3292.txt)
![screen shot 2017-04-10 at 11 45 35](https://cloud.githubusercontent.com/assets/18286650/24870723/3fb0d170-1de5-11e7-9633-8ab29936a018.png)
```
2.   SP1 <===>  VM <===>  SP2
      SP1 - URL: http://geni-orca.renci.org/owl/ion.rdf#AL2S/NCBI/Cisco/6509/GigabitEthernet/1/1
      SP1 - VLAN Tag: 1400
      SP2 - URL: http://geni-orca.renci.org/owl/ion.rdf#AL2S/Chameleon/Cisco/6509/GigabitEthernet/1/1
      SP2 - VLAN Tag: 3292
```
[request-stitchport-URLcham-URLncbi.txt](https://github.com/RENCI-NRIG/exogeni/files/910665/request-stitchport-URLcham-URLncbi.txt)
![screen shot 2017-04-10 at 11 55 45](https://cloud.githubusercontent.com/assets/18286650/24870798/7887d96c-1de5-11e7-9439-80e8b4e7cb45.png)

**Comment by hinchliff** [comment]
It looks to me like some changes to the Models during the reservation are causing the second Stitchport to fail.

Stepping through with the debugger, the first Stitchport seems to work just fine.  When the shortest path computation is started for the second Stitchport, the list of connected devices for the Stitchport is empty. (https://github.com/RENCI-NRIG/orca5/blob/orca-5.1.4/ndl/src/main/java/orca/ndl/OntProcessor.java#L705)

I noticed the [checkStitching()](https://github.com/RENCI-NRIG/orca5/blob/orca-5.1.4/embed/src/main/java/orca/embed/cloudembed/controller/InterDomainHandler.java#L244) code calls modifyRequestModel(), is some change being made there?  Or is the domain model (?) that is becoming corrupted?
