### ISSUE TITLE
Management interface uses 8139cp, not virtio

### ISSUE THREAD

**Issue by Bun** [RENCI-NRIG/orca5#128]
The management interface (eth0) requires the 8139cp kernel module instead of the virtio module that is used by all of the links provisioned in the slice request. I'm not sure if there's a technical reason for this.

This is a minor issue, but would save disk space since if all interfaces were virtio-based I could use a much, much smaller VM-specific kernel package (35MB vs 145MB).

**Comment by ibaldin** [comment]
Also related to the exogeni security issue RENCI-NRIG/exogeni#146

**Comment by ibaldin** [comment]
Related to Neuca code and ORCA tickets RENCI-NRIG/exogeni#58 and new Ubuntu images.

**Comment by ibaldin** [comment]
Misfiled as a source code issue - should be an exogeni issue with new option available to change which driver is used for managemnet plane.
