### ISSUE TITLE
NodeGroup increase modify requests are failing

### ISSUE THREAD

**Issue by hinchliff** [RENCI-NRIG/orca5#137]
This ticket is being forked from #122.  That ticket should be related to the TicketReview policy.  But in investigating that ticket, it was discovered that a different issue exists with NodeGroup modify requests.

Attempting to do a `Increase Node Group Size...` modify request results in the following exception:
```
java.lang.NullPointerException
	at orca.embed.cloudembed.MappingHandler.getIPRange(MappingHandler.java:199)
	at orca.embed.cloudembed.controller.ModifyHandler.addElements(ModifyHandler.java:459)
	at orca.embed.cloudembed.controller.ModifyHandler.modifySlice(ModifyHandler.java:139)
	at orca.embed.workflow.RequestWorkflow.modify(RequestWorkflow.java:249)
	at orca.controllers.xmlrpc.OrcaXmlrpcHandler.modifySlice(OrcaXmlrpcHandler.java:594)
```

Comparing to an older version (5.0.3) in emulation, new VM nodes were successfully added to the NodeGroup from an increase modify request, but errors were still reported in the logs:
```
INFO   | jvm 1    | 2017/06/01 14:01:08 | 2017-06-01 14:01:08,620 [qtp657982295-34] WARN  ndl.logger-(MappingHandler.java:186) - findIPRange,firstElement client interface is null!
INFO   | jvm 1    | 2017/06/01 14:01:08 | java.lang.Exception: group_base_ip is null!
INFO   | jvm 1    | 2017/06/01 14:01:08 |       at orca.embed.cloudembed.controller.ModifyHandler.addElements(ModifyHandler.java:461)
INFO   | jvm 1    | 2017/06/01 14:01:08 |       at orca.embed.cloudembed.controller.ModifyHandler.modifySlice(ModifyHandler.java:139)
INFO   | jvm 1    | 2017/06/01 14:01:08 |       at orca.embed.workflow.RequestWorkflow.modify(RequestWorkflow.java:249)
INFO   | jvm 1    | 2017/06/01 14:01:08 |       at orca.controllers.xmlrpc.OrcaXmlrpcHandler.modifySlice(OrcaXmlrpcHandler.java:609)
[...]
INFO   | jvm 1    | 2017/06/01 14:01:08 | 2017-06-01 14:01:08,622 [qtp657982295-34] INFO  ndl.logger-(ModifyHandler.java:471) - create new node from firstElement:i=0
INFO   | jvm 1    | 2017/06/01 14:01:08 | 2017-06-01 14:01:08,622 [qtp657982295-34] DEBUG ndl.logger-(ModifyHandler.java:498) - firstElement has no parent!
```

It looks like we have "improved" the situation by providing some of the required information in `firstElement`, but not enough to properly instantiate new VMs in the NodeGroup ?

I'm not sure what information we should expect/require to be in place for this sort of modify.

**Comment by hinchliff** [comment]
@YufengXin: this issue isn't really ready for a Pull Request yet, but could use your review.   I think the above changes will get us back to where we were, when NodeGroups could be increased in size successfully. 

Does this meet our expectations? Based on the warnings/exceptions thrown, _should_ this be working?  Is there additional information we expect/should have available at this point?

Or should we be failing in this section of code because of the missing information? (That we then need to fix elsewhere.)

Or does this code need to be more graceful in allowing success when not all of the information is present?

**Comment by YufengXin** [comment]
Thanks, Alan,

I’ll take a look later today to see what’s missed. The basic idea here was that, because arbitrary VMs in a node group can be added or removed, a IP address pool is maintained by the base IP address and a bitmap of the subnet space.


-Yufeng

**Comment by hinchliff** [comment]
OK, yes, using the new code, doing a NodeGroup Increase at the same time as a Delete doesn't seem to turn out quite right:
![nodegroup_increase_with_delete](https://cloud.githubusercontent.com/assets/10090677/26691861/b58ab55e-46cc-11e7-8599-ca5b82ebffea.png)

**Comment by hinchliff** [comment]
Actually, the above flukes diagram, where the added Nodes don't have network interfaces occurs with the simpler "only increase" type of modify.

**Comment by hinchliff** [comment]
I started a new branch for this issue: [new_137_nodegroup_modify](https://github.com/RENCI-NRIG/orca5/tree/new_137_nodegroup_modify), that uses the new Java 8 code.  (I started a new branch off master, and cherry-picked the commits from the old branch.)

**Comment by hinchliff** [comment]
@YufengXin this is what Flukes shows (in emulation) after the above fix.  Are these interface connections alright?

The request started with two NodeGroups, each of size one -- connected by a broadcast link, but without IP addresses being assigned.  The modify increased the size of one of the NodeGroups.

![issue_137](https://user-images.githubusercontent.com/10090677/29884669-2811e7cc-8d82-11e7-964a-aa44b964bade.png)

**Comment by YufengXin** [comment]
I think so. Each node group is supposed to be linked by individual broadcast link.

Thanks.

-Yufeng

**Comment by hinchliff** [comment]
@YufengXin i added another test for this -- where one nodegroup (_without_ Auto IP) is increased in size, the display in Flukes does not look correct.  Our unit test still passes with this test, so it seems that an interface is correctly being created.   Not sure if this might just be a display issue?

![137_1_1_no](https://user-images.githubusercontent.com/10090677/29894785-a7dc8706-8da4-11e7-8c64-b6e44a068121.png)

**Comment by YufengXin** [comment]
It might related to the link which is a Beast link instead of a p2p link. Would you send me the manifest to look at?

-Yufeng

**Comment by hinchliff** [comment]
@YufengXin here is the manifest: [137_one_nodegroups_of_size_one_noip_modify_manifest.txt](https://github.com/RENCI-NRIG/orca5/files/1266902/137_one_nodegroups_of_size_one_noip_manifest.txt)

**Comment by hinchliff** [comment]
For most of these examples, Flukes shows a different graph depending on whether the nodes were assigned IP Addresses (Auto IP) or not.

1. The NodeGroup of one Node, increased by one Node.  The non-IP is above, with IP it looks like this:
![137_1_1_ip](https://user-images.githubusercontent.com/10090677/29927764-48c4dd68-8e35-11e7-8684-5b07ea3c0385.png)

1. NodeGroups of two Nodes, increased by one Node:
![137_1_2](https://user-images.githubusercontent.com/10090677/29927788-57a1bd4c-8e35-11e7-9659-e24fe0c10d87.png)
![137_1_2_ip](https://user-images.githubusercontent.com/10090677/29927793-5cab8cc8-8e35-11e7-8d85-e514cacbb771.png)
Manifest for the No IP result: [137_one_nodegroups_of_size_two_autoip_modify_manifest.txt](https://github.com/RENCI-NRIG/orca5/files/1267352/137_one_nodegroups_of_size_two_autoip_modify_manifest.txt)

1. NodeGroups of size three, increased by one:
![137_1_3_no](https://user-images.githubusercontent.com/10090677/29927882-97b30b02-8e35-11e7-990d-6e72ad82cc42.png)
(With IPs, the graph is connected).
Manifest for the No IP result: [137_one_nodegroups_of_size_three_noip_modify_manifest.txt](https://github.com/RENCI-NRIG/orca5/files/1267362/137_one_nodegroups_of_size_three_noip_modify_manifest.txt)

1. NodeGroup of size one, increased by two
![137_1_1_noip_i2](https://user-images.githubusercontent.com/10090677/29927966-c67fbd40-8e35-11e7-9411-3c6bd8f1f129.png)
(Again, with IPs, the graph is connected).
Manifest for the No IP result: [137_one_nodegroups_of_size_one_noip_increase_2_manifest.txt](https://github.com/RENCI-NRIG/orca5/files/1267368/137_one_nodegroups_of_size_one_noip_increase_2_manifest.txt)

**Comment by hinchliff** [comment]
@YufengXin Looking at the manifest for the [one nodegroup of size one increased by one (noip)](https://github.com/RENCI-NRIG/orca5/issues/137#issuecomment-326117893) case, it looks to me like there are some inconsistencies in the manifest.

Line 1254 has this description for the VLAN.  Note there is a `hasInterface` for `NodeGroup0/0` on line 1262, but one is not present for `NodeGroup0/NoIP/c721cdaa-782c-4a42-a8af-d45635f87682`
```rdf
  <rdf:Description rdf:about="http://geni-orca.renci.org/owl/9de7a2c4-f834-47c4-bc15-7a9e8308d26b#VLAN0">
    <rdf:type rdf:resource="http://geni-orca.renci.org/owl/topology.owl#BroadcastConnection"/>
    <rdf:type rdf:resource="http://geni-orca.renci.org/owl/topology.owl#NetworkConnection"/>
    <rdf:type rdf:resource="http://geni-orca.renci.org/owl/topology.owl#LinkConnection"/>
    <j.3:inDomain rdf:resource="http://geni-orca.renci.org/owl/ncsuvmsite.rdf#ncsuvmsite/Domain/vlan"/>
    <j.3:message>Reservation d4eb92b4-f2a8-4c35-9ca7-622fd5bb92e7 (Slice 137_1_1_no) is in state [Active,None]
</j.3:message>
    <j.3:hasReservationState rdf:resource="http://geni-orca.renci.org/owl/request.owl#Active"/>
    <j.15:hasInterface rdf:resource="http://geni-orca.renci.org/owl/9de7a2c4-f834-47c4-bc15-7a9e8308d26b#VLAN0-NodeGroup0/0/intf"/>
    <j.15:hasGUID>3b5bde1d-9f70-48ec-a0ac-a0efabee609d</j.15:hasGUID>
    <j.8:hasResourceType rdf:resource="http://geni-orca.renci.org/owl/domain.owl#VLAN"/>
    <j.15:hasURL>http://geni-orca.renci.org/owl/ncsuvmsite.rdf#ncsuvmsite/Domain/vlan</j.15:hasURL>
    <j.2:atLayer rdf:resource="http://geni-orca.renci.org/owl/ethernet.owl#EthernetNetworkElement"/>
    <j.2:bandwidth rdf:datatype="http://www.w3.org/2001/XMLSchema#integer">10000000</j.2:bandwidth>
    <j.14:item rdf:resource="http://geni-orca.renci.org/owl/9de7a2c4-f834-47c4-bc15-7a9e8308d26b#NodeGroup0/0"/>
    <j.14:item rdf:resource="http://geni-orca.renci.org/owl/9de7a2c4-f834-47c4-bc15-7a9e8308d26b#NodeGroup0/NoIP/c721cdaa-782c-4a42-a8af-d45635f87682"/>
    <rdfs:label>128</rdfs:label>
  </rdf:Description>
```

Line 3348 has the ComputeElement for the new VM, but the `hasInterface` seems to refer to the old VM's interface.
```rdf
  <rdf:Description rdf:about="http://geni-orca.renci.org/owl/9de7a2c4-f834-47c4-bc15-7a9e8308d26b#NodeGroup0/NoIP/c721cdaa-782c-4a42-a8af-d45635f87682">
    <rdf:type rdf:resource="http://geni-orca.renci.org/owl/compute.owl#ComputeElement"/>
    <j.3:inDomain rdf:resource="http://geni-orca.renci.org/owl/ncsuvmsite.rdf#ncsuvmsite/Domain/vm"/>
    <j.3:message>Reservation e5ae645a-1fe6-482b-9d3b-3fdf8240d584 (Slice 137_1_1_no) is in state [Active,None]
</j.3:message>
    <j.3:hasReservationState rdf:resource="http://geni-orca.renci.org/owl/request.owl#Active"/>
    <j.15:hasInterface rdf:resource="http://geni-orca.renci.org/owl/9de7a2c4-f834-47c4-bc15-7a9e8308d26b#VLAN0-NodeGroup0/0/intf"/>
    <j.11:diskImage rdf:resource="http://geni-orca.renci.org/owl/9de7a2c4-f834-47c4-bc15-7a9e8308d26b#Centos+6.7+v1.1.0"/>
    <j.8:hasResourceType rdf:resource="http://geni-orca.renci.org/owl/compute.owl#VM"/>
    <j.15:hasURL>http://geni-orca.renci.org/owl/ncsuvmsite.rdf#ncsuvmsite/Domain/vm</j.15:hasURL>
    <j.11:hasRequestGroupURL>http://geni-orca.renci.org/owl/9de7a2c4-f834-47c4-bc15-7a9e8308d26b#NodeGroup0</j.11:hasRequestGroupURL>
    <j.4:hasParent rdf:resource="http://geni-orca.renci.org/owl/9de7a2c4-f834-47c4-bc15-7a9e8308d26b#VLAN0/NodeGroup0/NoIP/c721cdaa-782c-4a42-a8af-d45635f87682"/>
    <j.8:hasService rdf:resource="http://geni-orca.renci.org/owl/9de7a2c4-f834-47c4-bc15-7a9e8308d26b#NodeGroup0/NoIP/c721cdaa-782c-4a42-a8af-d45635f87682/Service"/>
  </rdf:Description>
```

Line 3766 has the Interface description for the old VM.  There doesn't seem to be a corresponding block for the new VM.
```rdf
  <rdf:Description rdf:about="http://geni-orca.renci.org/owl/9de7a2c4-f834-47c4-bc15-7a9e8308d26b#VLAN0-NodeGroup0/0/intf">
    <rdf:type rdf:resource="http://geni-orca.renci.org/owl/topology.owl#Interface"/>
    <j.15:hasGUID>94db4b01-b339-4913-9478-02430e2793db</j.15:hasGUID>
    <j.15:hasGUID>c26c5cd2-789e-4f55-97a3-fb7de1994ca3</j.15:hasGUID>
    <j.15:hostInterfaceName>data</j.15:hostInterfaceName>
    <j.5:localIPAddress rdf:resource="http://geni-orca.renci.org/owl/9de7a2c4-f834-47c4-bc15-7a9e8308d26b#VLAN0-NodeGroup0/0"/>
    <j.5:netmask>255.255.255.0</j.5:netmask>
    <owl:sameAs rdf:resource="http://geni-orca.renci.org/owl/9de7a2c4-f834-47c4-bc15-7a9e8308d26b#VLAN0-NodeGroup0"/>
    <owl:sameAs rdf:resource="http://geni-orca.renci.org/owl/9de7a2c4-f834-47c4-bc15-7a9e8308d26b#VLAN0-NodeGroup0/0/intf"/>
    <j.5:macAddress>fe:16:3e:00:c3:d6</j.5:macAddress>
  </rdf:Description>
```

Line 4022 has the ComputeElement description for the old VM.  Note it seems to have a correct `hasInterface` statement.
```rdf
  <rdf:Description rdf:about="http://geni-orca.renci.org/owl/9de7a2c4-f834-47c4-bc15-7a9e8308d26b#NodeGroup0/0">
    <rdf:type rdf:resource="http://geni-orca.renci.org/owl/compute.owl#ComputeElement"/>
    <j.3:inDomain rdf:resource="http://geni-orca.renci.org/owl/ncsuvmsite.rdf#ncsuvmsite/Domain/vm"/>
    <j.3:message>Reservation 79517eb5-877a-4f7f-aa61-d5a267e2e7cd (Slice 137_1_1_no) is in state [Active,None]
</j.3:message>
    <j.3:hasReservationState rdf:resource="http://geni-orca.renci.org/owl/request.owl#Active"/>
    <j.15:hasInterface rdf:resource="http://geni-orca.renci.org/owl/9de7a2c4-f834-47c4-bc15-7a9e8308d26b#VLAN0-NodeGroup0/0/intf"/>
    <j.11:diskImage rdf:resource="http://geni-orca.renci.org/owl/9de7a2c4-f834-47c4-bc15-7a9e8308d26b#Centos+6.7+v1.1.0"/>
    <j.8:hasResourceType rdf:resource="http://geni-orca.renci.org/owl/compute.owl#VM"/>
    <j.15:hasURL>http://geni-orca.renci.org/owl/ncsuvmsite.rdf#ncsuvmsite/Domain/vm</j.15:hasURL>
    <j.11:hasRequestGroupURL>http://geni-orca.renci.org/owl/9de7a2c4-f834-47c4-bc15-7a9e8308d26b#NodeGroup0</j.11:hasRequestGroupURL>
    <j.4:hasParent rdf:resource="http://geni-orca.renci.org/owl/9de7a2c4-f834-47c4-bc15-7a9e8308d26b#VLAN0/NodeGroup0/0"/>
    <j.8:hasService rdf:resource="http://geni-orca.renci.org/owl/9de7a2c4-f834-47c4-bc15-7a9e8308d26b#NodeGroup0/0/Service"/>
  </rdf:Description>
```
