### ISSUE TITLE
SSH into VM by handler doesn't work as expected on CentOS 6.9

### ISSUE THREAD

**Issue by ibaldin** [RENCI-NRIG/orca5#147]
@mcevik0 discovered on INNO rack that SSH into VM doesn't work as expected. @vjorlikowski hypothesized that this is due to changes made to return codes w/ and w/o TTY. Also related is that floating IPs aren't properly reclaimed on this error.

**Comment by mcevik0** [comment]
On existing script (nova_essex_common.py), when Popen is executed with "shell=False" in run method. When it was executed with "shell=True", it returned 255, too. 

I installed fabric (fabric-1.6.2-2.el6.noarch) and modified the _ssh_test_vm method as below. Now, return value is 0. 

```
    @classmethod
    def _ssh_test_vm(self, floating_addr, key, user, retries, timeout):

        if (os.environ['EC2_SSH_TIMEOUT']).isdigit() :
                ssh_timeout = int(os.environ['EC2_SSH_TIMEOUT'])
        else:
                ssh_timeout=20

        for i in range(retries):
            try:
                ssh_key = str(key)
                ssh_user = str(user)
                ssh_host = str(floating_addr)

                cmd = "/usr/bin/fab " +  "-D " + "-H " + ssh_host + " -i " + ssh_key + " -- echo"
                rtncode,data_stdout,data_stderr = Commands.run(cmd, timeout=ssh_timeout, shell=True)
                LOG.debug("--- DEBUG --- : ssh_test : " + str(data_stdout))

                if rtncode == 0:
                    return True

            except Exception as e:
                pass

            LOG.warning("Failed cmd: " + str(cmd) + ", retrying (" + str(i) + ")")
            time.sleep(timeout)

        if i >= retries:
            LOG.warning("Failed cmd  " + str(retries) + " times, giving up: " + str(cmd))
            return False
```

**Comment by ibaldin** [comment]
@mcevik0 @hinchliff what should we do about this ticket?

**Comment by mcevik0** [comment]
It will not affect any of the production racks right now. In my opinion, we can leave it now. 

This workaround is quite simple, installing fabric does not affect other stuff and the only change for the script is as above. But, I can try again to find a solution without fabric installation. (I want to check fabric code).

**Comment by mcevik0** [comment]
This is caused by a configuration problem on INNO rack. 
Permissions of /etc/orca/am+broker-12080/ec2/geni-orca was incorrectly set to 644 which caused ssh to fail. 
No changes are needed for the handler script.
