### ISSUE TITLE
Update docs for contributing

### ISSUE THREAD

**Issue by hinchliff** [RENCI-NRIG/orca5#149]
With @mjstealey coming on board, this is a good time to make sure our documentation is useful and up-to-date.

**Comment by ibaldin** [comment]
I would argue first we should document user-facing tools/libraries, like AHAB.

**Comment by hinchliff** [comment]
I wouldn't argue with that, except that so far everything that I have changed was documentation that I already needed to send to Michael.

**Comment by ibaldin** [comment]
Point taken. I did add a separate bullet RENCI-NRIG/ahab#6 for AHAB docs.
