### ISSUE TITLE
Failure to distinguish multi-point request when Node types are different, but in same domain

### ISSUE THREAD

**Issue by hinchliff** [RENCI-NRIG/orca5#157]
From RENCI-NRIG/exogeni#163:

> When a slice with 1 BM and 1 VM from Site1 connected to 1 BM from Site2 (by an broadcast link) is created, the BM from Site1 disappears on Flukes although that BM is active.

@YufengXin [commented](https://github.com/RENCI-NRIG/exogeni/issues/163#issuecomment-349476040):
> It is confirmed that this is underimplemented: in a multi-rack MP request, if two (or more than two) branches belong to the same domain but have two different resource types (vm or bm in the example), these branches would be aggregated into a node group with the first resource type picked. Then the manifest may also not handle this correctly.
see code in MultiPointHandler.java: function "ifMPConnection()"
Solution:
Option 1 (simple): slightly revise above ifMPConnection function, so that branches of different resource type will not be aggregated.
Option 2 (less simple): modify the NodeGroup definition so that it can contain elements of different resource type.

The plan is to fix this with option one: the resulting topology may be more complicated than necessary, but should be functional.

**Comment by ibaldin** [comment]
Option 1 is my vote. This is consistent with other stuff we do I think. Users do not expect NodeGroups to be VM/BM heterogeneous at this time.

**Comment by hinchliff** [comment]
The initial fix -- Option 1 -- basically works, but there seems to be a manifest / visualization issue when testing under emulation.

![157_mp_diff_resource_type](https://user-images.githubusercontent.com/10090677/33681017-5903dcc6-da91-11e7-99f1-08057c9ae2bb.png)
[157_mp_diff_resource_type_manifest.rdf.txt](https://github.com/RENCI-NRIG/orca5/files/1536579/157_mp_diff_resource_type_manifest.rdf.txt)
