### ISSUE TITLE
True-MultiPoint request with one unbound domain results in useless reservation

### ISSUE THREAD

**Issue by hinchliff** [RENCI-NRIG/orca5#158]
This probably isn't a very common use case, where a user requests a reservation with at least three specific domains and also one unbound domain:
![157_mp_mostly_bound_one_unbound_request](https://user-images.githubusercontent.com/10090677/33715552-f907268a-db20-11e7-8160-7c17a78c173b.png)

The resulting reservation is not very useful:
![157_mp_mostly_bound_one_unbound_manifest](https://user-images.githubusercontent.com/10090677/33715879-1e669ec8-db22-11e7-9ce0-a89ac44202df.png)
[157_mp_diff_resource_type_manifest.rdf.txt](https://github.com/RENCI-NRIG/orca5/files/1539075/157_mp_diff_resource_type_manifest.rdf.txt)

It's not too difficult to get Orca to basically give the user the bound multipoint reservations, and effectively ignore the unbound reservations.  Getting Orca to do both multipoint and unbound is probably more trouble than it's worth.

The main question here is probably whether we should silently "fail" and give the user the "valid" multipoint part of the request, or should we explicitly fail and return an error message to the user.

**Comment by ibaldin** [comment]
There are probably at least two choices:

1. Bind the unbound domain

2. Add a rule into request checker to reject requests like this

**Comment by hinchliff** [comment]
Yes, binding the unbound domain would probably be the right way to fix this, if we wanted to take the time.  It was not immediately apparent to me what the easiest way to do that would be, hence the feeling that it might be more trouble than it's worth -- since it's not that likely that a user would request this sort of reservation.

Which code are you referring to when you say the "request checker" ?

I have been looking at modifying the [`ifMPConnection`](https://github.com/RENCI-NRIG/orca5/blob/orca-5.2.1/embed/src/main/java/orca/embed/policyhelpers/RequestReservation.java#L285) function in RequestReservation.java (a slightly different function than the [one in MultiPointHandler](https://github.com/RENCI-NRIG/orca5/issues/157#issue-279815340), which would allow one to determine that the request is both true MultiPoint and also unbound.   This would allow an error to be returned in [RequestWorkflow.java](https://github.com/RENCI-NRIG/orca5/blob/orca-5.2.1/embed/src/main/java/orca/embed/workflow/RequestWorkflow.java#L142).

**Comment by YufengXin** [comment]
To block it in request is totally fine.


A simple first-fit heuristic could make it work: with the list of sites with available resources, just bind unbounded branch in order.

**Comment by hinchliff** [comment]
We don't have to fix this they way i just committed, but I figured I'd push it up here for possible review.
