### ISSUE TITLE
NodeGroup increase (modify) leads to visualization error

### ISSUE THREAD

**Issue by hinchliff** [RENCI-NRIG/orca5#178]
From RENCI-NRIG/exogeni#192

[From Ilya](https://github.com/RENCI-NRIG/exogeni/issues/192#issuecomment-353238026), it looks like the parent/`sameAs` information is not being correctly assigned.

-----------------------------------------------------------------------------------------------------
Testing RENCI-NRIG/orca5#122 on the orca-5.3.1 release, the NodeGroup increase seems to work as expected, but there may be a visualization issue in the resulting manifest.

Original request:
![122_request](https://user-images.githubusercontent.com/10090677/34227483-40500b54-e59b-11e7-99d4-e1497b376461.png)

Manifest view of original request:
![122_request_manifest](https://user-images.githubusercontent.com/10090677/34227489-49293728-e59b-11e7-91e5-ac8c85b4119a.png)

Manifest view after modify:
![122_modify_manifest](https://user-images.githubusercontent.com/10090677/34227503-578e9ccc-e59b-11e7-87ce-f277319237a9.png)
[122_modify_manifest.rdf.txt](https://github.com/RENCI-NRIG/exogeni/files/1576951/122_modify_manifest.rdf.txt)

The greyed out nodes are expected, as we tried to increase our nodegroup by more than resources allowed.

But the original two nodes are no longer shown as being connected.  If you login to the nodes, you can still ping between them using their 172.x addresses.  

-----------------------------------------------------------------------------------------------------

**Comment by hinchliff** [comment]
@ibaldin does the manifest from this look better?

[178_manifest.rdf.txt](https://github.com/RENCI-NRIG/orca5/files/1579685/178_manifest.rdf.txt)
![178_manifest_view_after_modify](https://user-images.githubusercontent.com/10090677/34262799-6151c7ac-e63b-11e7-84bf-22bbc0ab27db.png)

It looked to me, in the old manifest files, that _both_ the existing NodeGroup nodes and the new NodeGroup nodes had incorrect `sameAs` statements.  So I had to change the code in both [ModifyHandler](https://github.com/RENCI-NRIG/orca5/blob/orca-5.3.1/embed/src/main/java/orca/embed/cloudembed/controller/ModifyHandler.java#L592)
 and [CloudHandler](https://github.com/RENCI-NRIG/orca5/blob/orca-5.3.1/embed/src/main/java/orca/embed/cloudembed/controller/CloudHandler.java#L775).

I just noticed that the interface names are still awkward (e.g. `VLAN0-NodeGroup0/0/3/intf`) if I do Auto-IP on the request.  So I will need to further examine the best way to fix this.
[178_autoip_manifest.rdf.txt](https://github.com/RENCI-NRIG/orca5/files/1579711/178_autoip_manifest.rdf.txt)


That part of ModifyHandler seems to only be called in NodeGroup modify requests, while the CloudHandler code is called in every other type of create and/or modify request?

I really should take a closer look at whether those two functions need to be maintained separately, or if the code can be reused / combined.

**Comment by ibaldin** [comment]
I suspect that code is a cut-and-paste.

**Comment by hinchliff** [comment]
I think I have fixed the main issue with the interface `sameAs` statements, but the interface naming is still a little awkward.

In the change that I made, I was able to get the `sameAs` / parent interface ontology resource when appropriate, but I could not figure out how to get back to the [Interface that matches that Resource](https://github.com/RENCI-NRIG/orca5/blob/178_nodegroup_interface_sameas/embed/src/main/java/orca/embed/cloudembed/controller/CloudHandler.java#L733).  Is it possible to do this?   Updating the Interface reference might fix the interface naming.

**Comment by YufengXin** [comment]
In the manifest view, all the nodes have the same name “NodeGroup0”, before they were disguised by a “/x” appendix.

-Yufeng

**Comment by ibaldin** [comment]
This is an older version of Flukes. It should be proper now.

**Comment by ibaldin** [comment]
This wasn't a change in orca, it was a change in Flukes that caused the naming issue you're talking about @YufengXin You may need to restart/update flukes. 

The issue with interface names was described above. I think Alan was close to fixing it, I don't know what the latest status is. He was testing in the afternoon.
