### ISSUE TITLE
NEuca leaks quantum interfaces

### ISSUE THREAD

**Issue by ibaldin** [RENCI-NRIG/orca5#18]
During the most recent maintenance, I discovered a number of leaked quantum ports, on each of the AMs implementing storage.
These leaked ports were all associated with the storage network on these AMs.
It appears that the code that is supposed to clean up ports isn't doing so for the (statically defined) storage network.

**Comment by ibaldin** [comment]
Is this still an issue after we switched to OVS?

**Comment by vjorlikowski** [comment]
On Thu, Sep 22, 2016, at 12:26 PM, Ilya Baldin <notifications@github.com> wrote:
> Is this still an issue after we switched to OVS?
>

It should not be, any longer.
Management interfaces can still get leaked, though, in rare cases.

**Comment by ibaldin** [comment]
Closing, with prejudice!
