### ISSUE TITLE
Modify handler to test SSH connectivity only optionally

### ISSUE THREAD

**Issue by ibaldin** [RENCI-NRIG/orca5#181]
Off by default.

**Comment by ibaldin** [comment]
Now a property named ssh.key.insertion.soft.failure can be added to ec2 site properties to treat SSH key injection errors as soft (only logging) to support windows. It's not the default yet - the default is hard failure for the moment.

**Comment by ibaldin** [comment]
@mcevik0 Mert if you could test branch 181_ssh_optional on a standalone rack under the following conditions:

1. without modifying ec2.site.properties test that 
  - Linux images boot properly, keys are inserted into new instances
  - Adding new keys after the instance is booted also works (via new Flukes functionality)
  - Windows images will likely fail at the step when keys are inserted (but not at SSH connectivity test, which should not be run in this case due to absence of ARI or AKI)

(basically this tests that nothing is broken currently)

2. Modify ec2.site.properties and add a definition of property named ssh.key.insertion.soft.failure (give it any value). Then test the above scenarios and verify that Windows images boot now.

**Comment by mcevik0** [comment]
I pushed some changes to the branch 181_ssh_optional after testing on inno rack. 
These changes are mostly about indentation. 
- No major changes are made for logic although diff shows a significant amount of changes.
- Added a variable to catch the number of retries [here](https://github.com/RENCI-NRIG/orca5/blob/6dab409c23498426e6083db4ad4f19b8ad6a965d/handlers/ec2/resources/scripts/nova_essex_common.py#L1050)

All test cases are passed successfully.

**Comment by mcevik0** [comment]
- Python scripts are reformatted by PyCharm and pushed to 181_ssh_optional branch (RENCI-NRIG/orca5@2356289)
- I tested these scripts on inno rack. All test cases passed successfully.
