### ISSUE TITLE
XMPP PubSub may be dying randomly due to failures to catch NPE in xmpp-pubsub library

### ISSUE THREAD

**Issue by vjorlikowski** [RENCI-NRIG/orca5#187]
Need to integrate new version of xmpp-pubsub that fixes:

https://github.com/RENCI-NRIG/xmpp-pubsub/issues/1

Presuming that this fixes the XMPP PubSub issue, integrating a fixed version may also resolve:

https://github.com/RENCI-NRIG/exogeni/issues/156

**Comment by ibaldin** [comment]
We'll do a point release 5.4.1
