### ISSUE TITLE
Return netmask with the IP address in manifest

### ISSUE THREAD

**Issue by ibaldin** [RENCI-NRIG/orca5#20]
At some point in the future...

Current manifest doesn't contain the assigned netmask. Only the IP address. I would like to have both. Makes the job of auto-iping the modified slice much easier.

**Comment by hinchliff** [comment]
I tested this in emulation, and it looks like this is fixed:

I'm not sure why each IP address seems to be in the RDF twice. (Once with CIDR, and once without.)

>  <rdf:Description rdf:about="http://geni-orca.renci.org/owl/17cc7aff-f745-45c2-8b1f-c1694be93bbd#Link2-Node1/0">
    <rdf:type rdf:resource="http://geni-orca.renci.org/owl/ip4.owl#IPAddress"/>
    <j.6:label_ID>172.16.0.2/30</j.6:label_ID>
    <j.8:netmask>255.255.255.252</j.8:netmask>
  </rdf:Description>

>  <rdf:Description rdf:about="http://geni-orca.renci.org/owl/17cc7aff-f745-45c2-8b1f-c1694be93bbd#Link2-Node1-ip-172-16-0-2">
    <rdf:type rdf:resource="http://geni-orca.renci.org/owl/ip4.owl#IPAddress"/>
    <j.6:label_ID>172.16.0.2</j.6:label_ID>
    <j.8:netmask>255.255.255.252</j.8:netmask>
  </rdf:Description>
