### ISSUE TITLE
Handle cleaned up slices a little more gracefully in controller...

### ISSUE THREAD

**Issue by vjorlikowski** [RENCI-NRIG/orca5#200]
As slices are cleaned up - we get some of these exceptions in the controller:

```
INFO   | jvm 1    | 2018/02/13 20:47:35 | orca.controllers.OrcaControllerException: OrcaControllerException: unable to find slice mcevik-inno-20180213-204404 among active slices
INFO   | jvm 1    | 2018/02/13 20:47:35 |       at orca.controllers.xmlrpc.XmlrpcHandlerHelper.getSliceReservations(XmlrpcHandlerHelper.java:974)
INFO   | jvm 1    | 2018/02/13 20:47:35 |       at orca.controllers.xmlrpc.OrcaXmlrpcHandler.sliceStatus(OrcaXmlrpcHandler.java:469)
```

This just needs a try/catch at like 469 of OrcaXmlrpcHandler.

**Comment by kthare10** [comment]
This is already addressed in code. Code already contains a try/catch block to handle the exception

https://github.com/RENCI-NRIG/orca5/blob/4e216fc7ea78dbbfde8b5fb7e85ba281fec2d827/controllers/xmlrpc/src/main/java/orca/controllers/xmlrpc/OrcaXmlrpcHandler.java#L452
