### ISSUE TITLE
Error handling is insufficient for adding interfaces via modify

### ISSUE THREAD

**Issue by vjorlikowski** [RENCI-NRIG/orca5#209]
ORCA version is: orca-iaas-5.4.0_0_g0ece627-201801251206.

In /root/modify_failures_02_19_2018 (on tamu-hn), we have evidence of handler code not properly failing and returning errors upstream. This issue is a follow-on to: https://github.com/RENCI-NRIG/orca5/issues/208

At line 844 of: handlers/ec2/resources/handlers/ec2/handler.xml

We call the python script "neuca-quantum-add-iface" - but we do not properly handle errors that may have occurred as a result of its execution (so that they could be propagated upstream to ORCA).

As a result, modify attempts that add interfaces to VMs appear to succeed - despite having actually failed to properly perform the actions required for the modify request.

**Comment by vjorlikowski** [comment]
Please note - neuca-quantum-add-iface fails in two different ways, in: #208 
1) neuca-quantum-add-iface got handed a MAC that already exists in the VM, and errors out.
2) neuca-quantum-add-iface got handed something that *isn't a MAC* (e.g. "${modify.3.mac}"), and errors out.

neuca-quantum-add-iface should probably check to see if what's being handed to it is actually a MAC, and handler.xml should check the exit code of neuca-quantum-add-iface and DTRT.

**Comment by kthare10** [comment]
Fixed by pull request 218
