### ISSUE TITLE
Orca integration with Comet

### ISSUE THREAD

**Issue by kthare10** [RENCI-NRIG/orca5#212]
Use comet to pass properties to VM instead of ini files from AM. Using comet instead of ini files is a pre-requisite for the Openstack upgrade. This will ensure that no modifications are required in openstack.

Proposed Schema for Comet
![fieldmappings](https://user-images.githubusercontent.com/36123970/40858449-4ce032e0-65ac-11e8-9ddd-0c032149f7bd.png)

**Comment by kthare10** [comment]
JSON Schema for saving Users info in Comet. Users information will be stored in scopeValue field.

{
  "$id": "users.json",
  "type": "array",
  "items": {
    "$id": "users.json/items",
    "type": "object",
    "properties": {
      "user": {
        "$id": "users.json/items/properties/user",
        "type": "string",
        "title": "User Name",
        "default": "",
        "examples": [
          "root"
        ]
      },
      "sudo": {
        "$id": "users.json/items/properties/sudo",
        "type": "boolean",
        "title": "Flag indicating if user has sudo permissions",
        "default": false,
        "examples": [
          true
        ]
      },
      "key": {
        "$id": "users.json/items/properties/key",
        "type": "string",
        "title": "SSH Key for the user",
        "default": "",
        "examples": [
          "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDIxGUVBf24l4gSgUtQQaScP7S604CpXKh66cCMZB1GoXfGqyhRVO1xQUXGA2Oj8MeZf3bo4tjmrPnVeeTVfwTrxkkFNvekwY4QbGX7o8YPNnEFquLWMmkoLn9RFJI47Cj+JHWQN7sEW4WVnmHNITcw5lD3V+yw1bD5M0boUXvh/MnHTu59MEDRyLUyWY+N1FUxHrO0UgSISczRjFS31zF5WY83ssNWq+zxD0NM6GhLWg5Ynzat1J75NRvnMVkuj0VmFcJuHIl3jYCdL9uE7kCw08oh06p/VZBzUIDP6EB0e+H1udu0DvT7SunqBZnobrTCyj1Bma9BJEHPhocIIcPl komalthareja@dhcp152-54-6-178.wireless.europa.renci.org:\nkomalthareja=yes:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDIxGUVBf24l4gSgUtQQaScP7S604CpXKh66cCMZB1GoXfGqyhRVO1xQUXGA2Oj8MeZf3bo4tjmrPnVeeTVfwTrxkkFNvekwY4QbGX7o8YPNnEFquLWMmkoLn9RFJI47Cj+JHWQN7sEW4WVnmHNITcw5lD3V+yw1bD5M0boUXvh/MnHTu59MEDRyLUyWY+N1FUxHrO0UgSISczRjFS31zF5WY83ssNWq+zxD0NM6GhLWg5Ynzat1J75NRvnMVkuj0VmFcJuHIl3jYCdL9uE7kCw08oh06p/VZBzUIDP6EB0e+H1udu0DvT7SunqBZnobrTCyj1Bma9BJEHPhocIIcPl komalthareja@dhcp152-54-6-178.wireless.europa.renci.org:"
        ]
      }
    },
    "required": [
      "user",
      "sudo",
      "key"
    ]
  }
}

**Comment by kthare10** [comment]
JSON Schema for saving Users info in Comet. Users information will be stored in scopeValue field.
![users](https://user-images.githubusercontent.com/36123970/40921073-73002be2-67dc-11e8-8116-7cd1a14f5439.png)

**Comment by kthare10** [comment]
JSON Schema for saving Interfaces info in Comet. Interfaces information will be stored in scopeValue field.
![interfaces](https://user-images.githubusercontent.com/36123970/40921089-7e8516a8-67dc-11e8-92ac-8043701e0479.png)

**Comment by kthare10** [comment]
JSON Schema for saving Storages info in Comet. Storages information will be stored in scopeValue field.
![storages](https://user-images.githubusercontent.com/36123970/40921109-8e78f854-67dc-11e8-8b80-33347e241b9a.png)

**Comment by kthare10** [comment]
JSON Schema for saving Routes info in Comet. Routes information will be stored in scopeValue field.
![routes](https://user-images.githubusercontent.com/36123970/40921122-982d6f2e-67dc-11e8-9e0a-b7f49d0f7f6c.png)

**Comment by kthare10** [comment]
JSON Schema for saving Scripts info in Comet. Scripts information will be stored in scopeValue field.
![scripts](https://user-images.githubusercontent.com/36123970/40921137-a291d626-67dc-11e8-81ab-fc475ef8fbcb.png)

**Comment by ibaldin** [comment]
For users - we should be able to specify multiple SSH keys per user.

For routes - we probably should also add the 'via' and 'dev' options, like ip-route supports?

**Comment by kthare10** [comment]
Updated users and routes schema to incorporate the comments

**Comment by kthare10** [comment]
Setting up the Certificates on Comet Server once CA Cert, Server Cert and keys are generated:

1. Create CA Trusted Key Store from CA Certificate

`keytool -import -file DigiCertCA.crt -keystore comettrustedstore.jks`


2. Create Server Key Store from Server certificate and private key

`cat comet_exogeni_net.key star_exogeni_net.crt > cometserver.pem`

`openssl pkcs12 -export -in  cometserver.pem -out cometserver.pkcs12`

`keytool -importkeystore -destkeystore cometserver.jks -srckeystore cometserver.pkcs12 -srcstoretype PKCS12`

**Comment by kthare10** [comment]
Setting up the Certificates on AM once CA Cert, Client Cert and keys are generated:

1. Convert CA Cert to der format
`openssl x509 -in DigiCertCA.crt -out DigiCertCA.der -outform DER`

2. Create a jks key stor for client certificate and private key

`cat inno-hn_exogeni_net.key star_exogeni_net.crt > client.pem`

`openssl pkcs12 -export -in client.pem -out client.pkcs12`

`keytool -importkeystore -destkeystore client.jks -srckeystore client.pkcs12 -srcstoretype PKCS1`

**Comment by kthare10** [comment]
Changes merged to master
