### ISSUE TITLE
Further ORCA integration with COMET and neuca-guest

### ISSUE THREAD

**Issue by ibaldin** [RENCI-NRIG/orca5#217]
In order to support a broader range of functionality and have material for the paper we want to extend the functionality to support the following use-cases
- Ability to populate /etc/hosts files in groups of nodes in a slice (using information coming from the nodes)
- Ability to insert public SSH keys generated on the nodes (not by controller or AM) to support one-to-many, some-to-some and any-to-any SSH logins (e.g. Condor requires head-node to workers and Hadoop requires all-to-all)

**Comment by ibaldin** [comment]
From Komal
```
Further analysis for the global hostname configuration. I propose the following design (open to discussion/feedback).
Controller to create a global scope with ContextId(Slice-Id), Auto-generated (Key, ReadToken, WriteToken)
Auto-generated (Key, ReadToken, WriteToken) shared with all the AMs through configuration properties
AMs to save Auto-generated (Key, ReadToken, WriteToken) in all the VMs in global section of openstack meta data
Neuca-guest tool daemon on each VM :
update the Global scope with its IP Address information
Configure hostnames for host available with IP addresses in their /etc/hosts
 
Note: JSON schema for storing the hostname info enclosed with the mail.
 
Note: for now this only covers global slice scope, but can be later extended by adding scope for each hostname. Scope being controlled by location/site information of the VM or the network.
 
Enabling the feature on Neuca-Guest-Tools:
Always poll Global Scope
Process and configure hostnames if nodes array is present
Process and configure keys if keys array is present
For any future scopes; neuca-guest-tools could be enhanced for users to add process<Scope> functions if additional elements are read from Global scope
```

**Comment by ibaldin** [comment]
Picture based on discussion we further extended the concept above. 

![2018-07-27 11 53 46](https://user-images.githubusercontent.com/12304033/43346483-44b75bc2-91bf-11e8-99b8-0df230acf0ec.jpg)

**Comment by ibaldin** [comment]
Proposed schema for COMET

![comet-orca-extension](https://user-images.githubusercontent.com/12304033/43346734-58807214-91c0-11e8-91da-eec19bcb87d7.png)

Some rules that were derived for controller, AM and VM behavior:

- Each host group has a single common read token. However the write tokens are different for all VMs
- The hierarchy shown is created by the controller since visibility to whole slice is needed
- Controller will add property to all VM reservations that assigns it to a group. For now the group will be 'all', later we can extend flukes to provide user assigned group names (requires NDL extension)
- VM is passed the list of groups it needs to write to and read from. These correspond to suffixes in Family names above. The prefix matches a particular functionality in neuca guest tools that either reads information and fills out e.g. /etc/hosts or .ssh/authorized keys, or writes corresponding information into COMET.

**Comment by kthare10** [comment]
Refer to https://github.com/RENCI-NRIG/neuca-guest-tools/issues/5 for details on usage of neuca-guest-tools
