### ISSUE TITLE
semi-wedged slice on new compute node failure

### ISSUE THREAD

**Issue by paul-ruth** [RENCI-NRIG/orca5#49]
If you have an existing slice and modify it by adding a new compute node that does not have an image specified the vm will fail as expected.   The problem is that after you delete the failed vm and try to re-add the vm with an appropriate image the modify request fails silently.    In other words, the never appears in the slice (failed or otherwise).

To re-create:
1.  Create a slice with a single node
2. Create a modify request that adds a single node where the node does not specify an image.
3.  Query for the manifest and see the failed node.
4.  Delete the failed node with a modify request.
5.   Create a modify request that adds a single node where the node does specify an image.
6.  Query for the manifest and the new vm is not included.

**Comment by YufengXin** [comment]
fixed
