### ISSUE TITLE
Distinguishing node-level broadcast from domain multi-point connections

### ISSUE THREAD

**Issue by ibaldin** [RENCI-NRIG/orca5#70]
As per conversation with @paul-ruth and @YufengXin there is an overlap in meaning when selecting broadcast links as a link type when multiple domains are involved. The user implies broadcast behavior w.r.t. individual nodes, whereas controller interprets it as multi-domain and binds to DD. The controller needs to be smarter and avoid binding to DD if only one or two domains are involved. 

In this case there are restrictions on future modify behavior of such a connection, which probably should be resolved via break/make sequence (break two-point connection, replace with 3-or-more point connection bound to DD). Whether this behavior resides with the client library (AHAB) or the controller is still undecided. 

We also discussed leaving binding hints in the two or one-domain case above, where the user may leave an indication that this SHOULD be bound to DD based on future expected behavior of the slice.

**Comment by YufengXin** [comment]
roll back to treat 2-branch MP as a P2P. commit 0cc50f0370e5e8f9213d5ffd1e805c51553c16cc.
