### ISSUE TITLE
Modifying broadcast links in multi-domain slices

### ISSUE THREAD

**Issue by ibaldin** [RENCI-NRIG/orca5#71]
Having a two- or three- or more domain slice, one should be able to add nodes to existing sites once the slice is created. Basically attaching nodes to existing rack-local VLANs that are already part of the slice should work and currently does not.

Testing scenarios should involve two-domain and three-domain cases (create a two- or three-domain slice, try to add nodes to existing rack-local VLANs).

@YufengXin thinks this is a manifest issue. Also tagging @paul-ruth

**Comment by YufengXin** [comment]
This appears to be a Flukes visualization issue: after new nodes add to the rack-local VLAN, the vlan sliver has more than two interfaces. However, it is not a broadcast and does not show all the links.

I ran a simple test: a BBN to FIU dumb bell first, then add a new node to the bbnNet vlan. I ping the new node and manifest RDF looks right to my eye.  

@paul-ruth, because you application does not need Flukes, rather on the manifest itself, could you run a test to see if it actually works for your code. And first check if you can the added node.

I and Ilya will discuss this and take a closer look.

**Comment by ibaldin** [comment]
I tried a test with 3 nodes on each side PSC/BBN initially (total of 6) with broadcast link in between. That succeeds. Then adding one more node on PSC side results in a garbled manifest, however the new node is created and is properly connected. 

![screen shot 2016-09-28 at 1 17 19 pm](https://cloud.githubusercontent.com/assets/12304033/18924360/ecfbc98a-857d-11e6-9a42-e34aa81d12f3.png)

**Comment by ibaldin** [comment]
Ilya to look at manifest for a simple two-node case to see what is missing.

**Comment by ibaldin** [comment]
The culprit lies in the fact that when a node is added to an existing VLAN, that VLAN now also becomes 'NetworkConnection' in the manifest:
```
 <rdf:Description rdf:about="http://geni-orca.renci.org/owl/bbnNet.rdf#bbnNet/Domain/vlan/cbe1ba28-03df-4ae9-8662-e759381e10e4/vlan">
 
    <rdf:type rdf:resource="http://geni-orca.renci.org/owl/topology.owl#NetworkConnection"/>


    <j.16:hasInterface rdf:resource="http://geni-orca.renci.org/owl/355536cc-b5c8-4ee2-a277-bbc0c5bb74fd#Link20-Node0"/>
    <j.16:hasInterface rdf:resource="http://geni-orca.renci.org/owl/bbnNet.rdf#BbnNet/IBM/G8052/TenGigabitEthernet/1/1/ethernet"/>
    <j.16:hasInterface rdf:resource="http://geni-orca.renci.org/owl/bbnNet.rdf#BbnNet/IBM/G8052/GigabitEthernet/1/0/ethernet"/>
    <j.16:hasInterface rdf:resource="http://geni-orca.renci.org/owl/8d76aceb-672c-471a-b6a6-deb2ed14572b#bbnNet/Domain/vlan/cbe1ba28-03df-4ae9-8662-e759381e10e4/vlan-Node2"/>
    
    <j.12:item rdf:resource="http://geni-orca.renci.org/owl/8d76aceb-672c-471a-b6a6-deb2ed14572b#Node2"/>

    <j.9:hasReservationState rdf:resource="http://geni-orca.renci.org/owl/request.owl#Active"/>
    <rdf:type rdf:resource="http://geni-orca.renci.org/owl/topology.owl#CrossConnect"/>
    <j.9:inDomain rdf:resource="http://geni-orca.renci.org/owl/bbnNet.rdf#bbnNet/Domain/vlan"/>
    <j.9:message>Reservation 80903bd4-8cc1-4bb4-882e-d5081eccdbf7 (Slice modify-test-1) is in state [Active,None]
</j.9:message>
    <j.16:hasURL>http://geni-orca.renci.org/owl/bbnNet.rdf#bbnNet/Domain/vlan/cbe1ba28-03df-4ae9-8662-e759381e10e4/vlan</j.16:hasURL>
    <j.1:inRequestNetworkConnection rdf:resource="http://geni-orca.renci.org/owl/355536cc-b5c8-4ee2-a277-bbc0c5bb74fd#Link20"/>
    <j.13:hasResourceType rdf:resource="http://geni-orca.renci.org/owl/domain.owl#VLAN"/>
    <j.7:bandwidth rdf:datatype="http://www.w3.org/2001/XMLSchema#integer">10000000</j.7:bandwidth>
    <j.16:inConnection rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean">true</j.16:inConnection>
    <rdfs:label>2601</rdfs:label>
    <j.6:quantumNetUUID>2408b413-40ae-4bbf-bb64-7f37e75762eb</j.6:quantumNetUUID>
  </rdf:Description>
```

which forces the ManifestParser to skip it. 

This is fixed in manifest parser now and the new parser is deployed into Nexus, however the code is not yet committed, because other changes are coming. Tested for inter- and intra- rack slices with storage and seems to work fine. 

@paul-ruth

**Comment by ibaldin** [comment]
Fixed in 620441c

**Comment by mcevik0** [comment]
After updating ExoSM for RENCI-NRIG/orca5@6011a0b , tests are executed to check all previous issues.
Errors received for the case stated on this issue:
- Slice connecting PSC and BBN, 3 nodes in each site, broadcast link connecting all 6 nodes created.
- 2 nodes (PSC rack) are missing in the manifest, exception reported on 2 nodes 
- Manifest is attached: 
[multi-domain-broadcast-link.txt](https://github.com/RENCI-NRIG/orca5/files/558927/multi-domain-broadcast-link.txt)

**Comment by ibaldin** [comment]
This may be a different issue than described in this ticket. Please stay tuned.

-

**Comment by ibaldin** [comment]
This ticket will stay opened until #80 is fixed, until then this can't be tested.

**Comment by ibaldin** [comment]
We should test this with a two-site/two-node case and leave #80 be for the moment.

**Comment by YufengXin** [comment]
Hi, Ilya,

I think I fixed this problem (again rooted in the conversion from p2p MP to p2p). I’ve tested all the previous related test cases in Emulator.
Pls let me know if you have checked in all you have, then I’ll check in, so it is easy to roll back in case more problems.




Yufeng Xin, PhD
RENCI
UNC at Chapel Hill
1-919-445-9633
yxin@renci.org <mailto:yxin@renci.org>

**Comment by ibaldin** [comment]
Everything I have is checked in



Sent from my Verizon 4G LTE smartphone


-------- Original message --------

**Comment by mcevik0** [comment]
ORCA rebuilt (RENCI-NRIG/orca5@0941f06)
- geni.renci.org: RPMs updated. Controller JVM stateful-restarted.

**Comment by mcevik0** [comment]
Test:
Create two nodes on each of two sites, connect all of the nodes with a broadcast-link: Succeeded.

<img width="1312" alt="screen shot 2016-10-31 at 09 53 38" src="https://cloud.githubusercontent.com/assets/18286650/19856560/5fcb78b6-9f50-11e6-8323-a64961b099a2.png">

**Comment by mcevik0** [comment]
Test: 
Create _three_ nodes on each of two sites, connect all of the nodes with a broadcast-link: Succeeded.

**Comment by ibaldin** [comment]
By all indications works in emulation. Tested adding a link to existing node from Net VLAN and then adding a new node to Net VLAN. Invocations of the handler for modify add interface and add node look correct. Closing.
