### ISSUE TITLE
Create docker images

### ISSUE THREAD

**Issue by hinchliff** [RENCI-NRIG/orca5#83]
The proposed idea is to make docker image(s) to run Orca, with the following benefits:

1. Allow developers to test Orca on their local machine, without using the VM
1. Jenkins can use the Docker images for CI

It is possible for Maven to build the docker images ([docker-maven-plugin from Spotify?](https://github.com/spotify/docker-maven-plugin)), so ideally we would probably have Maven both create the RPMs ([rpm-maven-plugin from mojohaus?](http://www.mojohaus.org/rpm-maven-plugin/)) and the docker images.

This article from Alooma seems to provide a nice look at using Maven to build Docker images: [Building Dockers with Maven for Continuous Integration](https://www.alooma.com/blog/building-dockers)

But for initial testing, we will keep the current RPM building alone, and see if we can get docker images to build manually.

Ideally, again, we would probably have at least four containers:

1. Orca SM
1. Orca AM + Broker
1. Orca Controller
1. MySQL

But initial testing seems to show that Orca doesn't expose the configuration to use a 'remote' MySQL server, expecting to find it on localhost.  For now, each of the other other three containers will run their own mysql server.

**Comment by vjorlikowski** [comment]
On Fri, Nov 11, 2016, at 04:16 AM, hinchliff wrote:
> It is possible for Maven to build the docker images
> ([docker-maven-plugin from
> Spotify?](https://github.com/spotify/docker-maven-plugin)), so
> ideally we would probably have Maven both create the RPMs
> ([rpm-maven-plugin from
> mojohaus?](http://www.mojohaus.org/rpm-maven-plugin/)) and the
> docker images.
>

So - *do* give the rpm-maven-plugin a shot - but...

I looked into it, "way back when" - and I chose to author the
buildrpm script instead, because shoehorning ORCA's build into a
"standard" RPM build that the Maven plugin could understand looked
like it would be particularly unpleasant.

The Maven RPM plugin looks (to me) like it was designed for the 80%
case (simple-to-moderate complexity RPM builds) - but makes building
complex RPMs hard-to-impossible.

Feel free to prove me wrong on that one, though. ;)

**Comment by hinchliff** [comment]
Well, yeah, that's part of why I'm leaving that piece alone for now :)

**Comment by hinchliff** [comment]
Actually I figured out (at least one hack) to get MySQL into a separate container. I started a new branch to track the code: [docker](https://github.com/RENCI-NRIG/orca5/tree/docker).

There is a lot of configuration stuff here that I am muddling through.  I'm not sure how accurate the [installation:details](https://wiki.exogeni.net/doku.php?id=private:installation:details) page is?

**Comment by mcevik0** [comment]
Installation details are quite accurate, some caveats exist mostly about xCAT configuration. I can help for each step, installing, configuring etc.

**Comment by hinchliff** [comment]
My SM container is currently giving this error, and I'm not even sure where to start looking.  Is this a configuration problem?  Or a dependency problem?

> INFO   | jvm 1    | 2016/11/11 16:23:14 | orca.shirako.container.ContainerInitializationException: java.lang.IllegalStateException: BeanFactory not initialized or already closed - call 'refresh' before accessing beans via the ApplicationContext

**Comment by ibaldin** [comment]
This looks like possibly an axis issue. Perhaps keystores aren't properly initialized.



Sent from my Verizon 4G LTE smartphone


-------- Original message --------

**Comment by hinchliff** [comment]
Well, Mert gave me some updated JKS files, and it seems like maybe my controller can talk to the SM now.  But I get this error when I try to create a new slice.  The error can be seen both in Flukes, and in the AM+Broker log:

> Reservation b5731f07-0484-430e-91e4-742cfc99ef34 (Slice hincha.emulation) is in state [Failed,None] Last lease update: all units failed priming: Exception during join for unit: 8AFE6F7D Execute failed: java.io.IOException: Cannot run program "/etc/orca/am+broker-12080//packages/pkg/87DBB2BE-7977-4463-A0CB-F6043735DEF9/scripts//${cloud.type}-start" (in directory "/etc/orca/am+broker-12080/handlers/ec2"): error=2, No such file or directory

Mert suggested I needed to copy the extra properties files (e.g. ec2.site.properties) into the am+broker config directory.  I copied the properties files from the emulation VM, but I still get the same error.

**Comment by ibaldin** [comment]
You need to either turn on emulation or specify the ec2 properties, among which is cloud.type

You can see how it is done on any operational rack config.



Sent from my Verizon 4G LTE smartphone


-------- Original message --------

**Comment by hinchliff** [comment]
Well, I have "emulation=true" in both the am+broker and the sm config (orca.properties) ...  Is there somewhere else I need to turn it on?

**Comment by ibaldin** [comment]
It may be that the cloud type needs to be specified anyway. look at handlers/ec2/resources/handlers/ec2/handler.xml and follow the 'join' target logic.



Sent from my Verizon 4G LTE smartphone


-------- Original message --------

**Comment by hinchliff** [comment]
Hmmm... yes, I can't figure out where (at least in my copy) the emulation VM sets cloud.type.  But if I set that value, I can create a new slice and get a green node!

I think that means this is working now.  I need to figure out what the best thing to do with all of the config files is going to be.  I don't think checking them into git will be the right thing -- we may just want to have the config directories be Volume mounts when the docker container runs...

Now that this is sort of working, I can try to get Maven to build the docker images.

**Comment by ibaldin** [comment]
Keeping config separate is preferred. The rpms I thin set up a basic structure, but leave you to admin to populate. The source tree has done examples of config files but they are near the places that use them, not where they are usually deployed.



Sent from my Verizon 4G LTE smartphone


-------- Original message --------

**Comment by hinchliff** [comment]
I added maven building in commit 2044148277f9c6010f04aab45d3f287c82fb7023.

It's currently dependent upon you having built the RPMs manually.  (And I haven't modified the parent pom, or pushed to master yet.) Could probably fix the manual RPM build with an maven ant-run to build the RPMs?  Or perhaps I should look into the rpm-maven-plugin next.

**Comment by hinchliff** [comment]
Currently, the docker images still need a minor change to the orca-iaas.spec file, because I am only installing the JRE on the images, and not the full JDK (even when using Oracle Java).
