### ISSUE TITLE
How should we do Releases?

### ISSUE THREAD

**Issue by hinchliff** [RENCI-NRIG/orca5#85]
You may have noticed that I cut a release of Orca today.  Ilya and I talked briefly about doing it this morning -- it seems like the code base has been pretty stable recently.  Really, it probably would have been nice to tag the release before you all went to SC16, but better late than never?

I wanted to be able to keep track of specific versions as we move forward, as we start to try to do other code cleanup / refactoring.

I used the maven-release-plugin to do the release today, since that was already basically setup in the pom.  I think it would make sense to move the release process to a Jenkins plugin.  

Moving forward, I think all of the following would be good to have:

1. Releases are manual events, initiated in Jenkins (completed by Jenkins plugin).
1. RPMs are built from the tagged release commit.
1. Any time we want to deploy updated RPMs to a system, we perform a release.
1. RPMs (and Docker images) are built by Jenkins for every commit/push, not just releases (for future Integration Testing).

Thoughts?

(Do enough people get auto-notifications for new issues?  Or do I need to manually tag people?)

**Comment by hinchliff** [comment]
On version numbers themselves, [Semantic Versioning](http://semver.org/) is probably the ideal to aim for.

**Comment by ibaldin** [comment]
I think I’m on board with all of this. One question is - is there a ‘flag day’ or do we do this gradually per project? Some dependencies may get in the way.

-ilya

**Comment by hinchliff** [comment]
> One question is - is there a ‘flag day’ or do we do this gradually per project? Some dependencies may get in the way.

In general, I think we should be doing this gradually / frequently per project.    If say, I update node-agent2:agentlib to a new version, it doesn't directly affect Orca, until I update Orca to pull the newest version of agentlib.

Semantic Versioning is supposed to give you a sort of 'contract' between projects and dependent libraries.  Each library/project should update the version number appropriately to indicate whether there are breaking API changes; or just simple bug fixes.

In practice of course it will probably get more complicated.  A dissenting viewpoint is here: [Why Semantic Versioning Isn't](https://gist.github.com/jashkenas/cbd2b088e20279ae2c8e). But it doesn't really offer a better solution -- just suggests that Semantic Versioning won't automatically make everything perfect.

We will need to take the time, at some point / regularly, to go through our projects to see if there are newer versions of libraries that we should be upgrading too.  Semantic Versioning is supposed to give you some indication of whether the new dependency version "should just work, with fewer bugs" vs. "might require code changes in order to use new features".

**Comment by ibaldin** [comment]
Should we close this, as it seems we've moved into using Semantic Versioning?

**Comment by hinchliff** [comment]
Yes, probably.  Closing now.
