### ISSUE TITLE
Probable bugs: String comparison using '==', instead of 'equals()'

### ISSUE THREAD

**Issue by hinchliff** [RENCI-NRIG/orca5#87]
20 Warnings total, spread across these files:

> BenNdlPropertiesConverter
> ConnectionManager
> DomainElement
> DriverFactory
> InterDomainHandlerTest
> NetworkHandler
> NetworkHandlerTest
> NlrNdlPropertiesConverter
> OntProcessor
> PropertiesConverter
> RequestMapping
> RequestReservation

The ones where the comparison is "" would probably work best as a call to isEmpty()

**Comment by ibaldin** [comment]
Feel free to fix, but they are probably not genuine bugs.

-ilya
