### ISSUE TITLE
Resource Exhaustion Behavior

### ISSUE THREAD

**Issue by hinchliff** [RENCI-NRIG/orca5#88]
This ticket is being split off from #36.  The old ticket should be used to track intra-domain bandwidth exhaustion behavior, while this ticket should be used specifically for the behavior noticed by Anirban and Paul, where [accounting of XL VMs is in error](https://github.com/RENCI-NRIG/orca5/issues/36#issuecomment-256460555).

**Comment by hinchliff** [comment]
Apparently this [error I get from the Broker](https://github.com/RENCI-NRIG/orca5/issues/36#issuecomment-267995150) is the correct behavior.  The broker seems to be doing the right thing, if I start a new slice and ask for enough XOXLarge VMs to be too large for the available resources.

@anriban @paul-ruth -- could you tell me more about what I need to do to reproduce this problem?

**Comment by anriban** [comment]
There is one side effect I observed - Suppose I am using all the cores on a particular rack in a single slice using all XL vms. If I query for available resources using flukes, it shows some cores as available even if I know that I am using all cores available through the rack SM. I launched the slice with the rack controller.

Given this observed behavior, the problem might be replicated by launching one slice that uses all the cores with XL vms and then trying to launch another slice on top of it with just one xo medium VM .. then check if that goes through, and if not , who rejects it - the broker or the am..

**Comment by hinchliff** [comment]
Thanks @anriban.

In my docker emulation environment, I started creating some slices in a domain that listed 36 VMs available.

First I created a slice with 9 XL VMs.  After this, Flukes still thinks 27 VMs are available in the domain.

Next I tried to create a slice with 1 M VM.  This was not successful, with Flukes showing the following:

> hincha0
Failed 
Reservation e2d35f61-790f-4e65-86b6-3b1f4d49e862 (Slice hincha-1482417102-1M) is in state [Failed,None] Last ticket update: java.lang.RuntimeException: Insufficient   to meet request:3000
No management access
>
> net1
Active 
Reservation bb6cc5cf-ff96-4731-8816-2cda6f1bf44c (Slice hincha-1482417102-1M) is in state [Active,None]
No management access

The broker logs include an error basically the same as [previously](https://github.com/RENCI-NRIG/orca5/issues/36#issuecomment-267995150) 

>2016-12-22 14:31:51,232-[test-ndl-broker]-{ERROR}-orca.test-ndl-broker-(BrokerSimplerUnitsPolicy.java:281)-Failed to ticket: slvmsite.vm for slice: hincha-1482417102-1M
java.lang.RuntimeException: Insufficient <memoryCapacity,0> to meet request:3000
        at orca.plugins.ben.broker.NDLVMInventory.allocate(NDLVMInventory.java:111)

@YufengXin @ibaldin is this the expected behavior?  Is this the _desired_ behavior?  Note that the slice is partially created -- in this example, only the Network is created; but if there had been a request for a larger number of VMs, some of them could have been created if the resources existed, while others would have failed.

**Comment by ibaldin** [comment]
@hinchliff Alan, please clarify which slice was partially created?

**Comment by hinchliff** [comment]
The slice with 1 VM was partially created -- the network is active, and the node/VM is failed.   The slice with 9 XL VMs (and 1 vlan) was created completely/successfully.

**Comment by hinchliff** [comment]
One thing that hadn't completely clicked in my head until this week was that the node/vm and the net/vlan are two separate reservations.  Only the node/vm is failing from resource exhaustion, and the net/vlan is still being ticketed and redeemed.

Where / Is there a check for whether all of the reservations/tickets have been successful for a given slice?  Would this be the best way to check for this error (if any of the reservations/tickets for this slice has failed, then cancel all of the other reservations/tickets for the entire slice)?

**Comment by ibaldin** [comment]
I don’t know that this check exists today and based on our earlier discussions, it seems like it is necessary. @YufengXin should probably voice his opinion on this. I’m guessing it can be either on SM policy side or in the controller.

**Comment by YufengXin** [comment]
The discussion on wether failing the whole slice due to a few failed slivers or not surfaced a couple of times in the past. There were concerns for large slices if doing so. Maybe now it is a good time to revisit this policy given ExoGENI is much more stable than before. Implementing such a policy in controller  should be easy, could be part of the manifest generation. It could be an optional policy that users can specify in the request.


-Yufeng

On Jan 4, 2017, at 2:51 PM, Ilya Baldin <notifications@github.com<mailto:notifications@github.com>> wrote:

I don’t know that this check exists today and based on our earlier discussions, it seems like it is necessary. @YufengXin should probably voice his opinion on this. I’m guessing it can be either on SM policy side or in the controller.

**Comment by ibaldin** [comment]
It would be good to sit down and discuss. I’ll schedule a meeting.
-ilya

**Comment by hinchliff** [comment]
The decisions from the meeting, we should:

1. Change default controller policy to behave same for exceeding unit counts and constraints.
1. Change return object behavior for [createSlice()](https://github.com/RENCI-NRIG/orca5/blob/master/controllers/xmlrpc/src/main/java/orca/controllers/xmlrpc/OrcaXmlrpcHandler.java#L239) and [modifySlice()](https://github.com/RENCI-NRIG/orca5/blob/master/controllers/xmlrpc/src/main/java/orca/controllers/xmlrpc/OrcaXmlrpcHandler.java#L536) to support per-request-object status.  
   * Report the Aggregate (AM?) and constraint limit(s) (to user, if possible).  
   * Need to distinguish from ticket count (unit count) vs. constraint violations.
1. Write a short proposal on how the above will be implemented.

I will need to double check a few things:

- Previous testing only exercised createSlice(), need to test current behavior for modifySlice().
- Need to double check broker control policy for all constraint types.
- Investigate how hard it would be to report every constraint that was/would be violated.

**Comment by hinchliff** [comment]
Taking a quick look at the three bullets points that needed to be double checked:

- Behavior in modifySlice() is essentially identical -- same behavior and same error messages.
- The `BrokerSimplerUnitsPolicy` function [ticket()](https://github.com/RENCI-NRIG/orca5/blob/master/core/policy/src/main/java/orca/policy/core/BrokerSimplerUnitsPolicy.java#L253) has the very simple comparison for Units (VMs or Vlans).  The units are handled identically.  Constraints are explore in the next bullet.
-  VMs and Vlans constraints are handled in two separate classes:
   - For VMs, the `NDLVMInventory` function [allocate()](https://github.com/RENCI-NRIG/orca5/blob/master/plugins/ben/src/main/java/orca/plugins/ben/broker/NDLVMInventory.java#L83) checks the three constraints (CPU Cores, RAM, Storage). The first constraint to fail throws an exception.
   - For Vlans, the `NDLVlanInventory` function [allocate()](https://github.com/RENCI-NRIG/orca5/blob/master/plugins/ben/src/main/java/orca/plugins/ben/broker/NDLVlanInventory.java#L73) checks the one constraint (Bandwidth).  If the constraint fails, it throws an exception.

It would not be very difficult to modify the [allocate()](https://github.com/RENCI-NRIG/orca5/blob/master/plugins/ben/src/main/java/orca/plugins/ben/broker/NDLVMInventory.java#L83) function in `NDLVMInventory` to check against all three constraints before failing, but it could be difficult to return that information all the way to the controller in a meaningful way.

**Comment by ibaldin** [comment]
I may be missing something, but it seems the solution may need to be on controller side, hiding the fact that answers from the broker are different in the case of violating a ticket count vs violating a constraint.

**Comment by hinchliff** [comment]
No, I don't think you're missing anything.  The controller (createSlice() and modifySlice()) will need to be modified to support this ticket.

The additional bullets were really just double-checking some assumptions, and investigating the desire to include additional information that is not currently available.

The numbered list will be covered in the proposal...

**Comment by hinchliff** [comment]
@ibaldin @paul-ruth @YufengXin

Proposal:

1) The Controller currently aborts the `createSlice()` or `modifySlice()` if the Unit counts are exceeded, cancelling the `create` or `modify`.  The Controller policy will be changed for Constraint violations to behave in the same manner, aborting the `create` or `modify` if the Constraints are violated for any constituent reservations.
   - Unit failure occurs at the '[workflow](https://github.com/RENCI-NRIG/orca5/blob/orca-5.0.3/controllers/xmlrpc/src/main/java/orca/controllers/xmlrpc/OrcaXmlrpcHandler.java#L338)' stage in the controller.  This will probably remain unchanged, returning an error at Line 354 ([Line 618](https://github.com/RENCI-NRIG/orca5/blob/orca-5.0.3/controllers/xmlrpc/src/main/java/orca/controllers/xmlrpc/OrcaXmlrpcHandler.java#L618) for `modify`).  (I'm not sure if I can get access to the details on all of the constituent reservations.  If I can, I can add further information to more closely match the error condition of the Constraint failure.)
   - Constraint failure can only be detected after [SliceDeferThread.processSlice()](https://github.com/RENCI-NRIG/orca5/blob/orca-5.0.3/controllers/xmlrpc/src/main/java/orca/controllers/xmlrpc/OrcaXmlrpcHandler.java#L394). There is an iterator over all of the reservations ([LeaseReservationMng](https://github.com/RENCI-NRIG/orca5/blob/orca-5.0.3/core/shirako/src/main/java/orca/manage/beans/LeaseReservationMng.java)) starting at Line 399 ([Line 1042](https://github.com/RENCI-NRIG/orca5/blob/orca-5.0.3/controllers/xmlrpc/src/main/java/orca/controllers/xmlrpc/OrcaXmlrpcHandler.java#L1042) for `modify`).  We should be able to add a check here for failed reservations, and start reacting accordingly.

2) The `createSlice()` and `modifySlice()` methods currently return a Map<String, Object> with the following three possible entries:
- Key: `ERR_RET_FIELD` ("err") → (boolean) true/false
- Key: `MSG_RET_FIELD` ("msg) → (String) "ERROR: " + `msg`. _Only present in error conditions_
- Key: `RET_RET_FIELD` ("ret") → (String) "Here are the leases: " + [etc]. _Only present in success conditions_

Proposal will keep those three fields present, and basically unchanged.  Will add the following additional fields for success or Constraint failure, whenever necessary and available:
- Key: `"failedRequestEntities"` → (Map<String, Object>) _Will only be present when an Error occurs_
- Key: `"ticketedRequestEntities"` → (Map<String, Object>) _Will be present on success.  May be present on error (for ticketed but not redeemed reservations)_
- The new fields are both Maps, with an Entry for each Reservation as follows:
   - Key: reservation GUID →(Map<String, Object>)
      - Key: `"Reservation State"` → (int) e.g. Failed/Ticketed
      - Key: `"Reservation Notice"` → (String) _Should contain error from Broker on Failed reservations_
      - Key: `"Slice UID"` → (String)
      - Key: `"Resource Type"` → (String)
      - Key: `"Resource Units"` → (int)

If other information about the Reservation is useful and available in the Controller at this point in the code, please let me know.

I plan on starting to work on this issue by creating some test(s) for the `createSlice()` and `modifySlice()` methods, and after that making changes to the code.

Does this look ok?

The one thing I'm not sure about is whether all Reservations will, at this point in the code, have a State of either Failed or Ticketed.  Will some of them be Nascent (or some other state)?  Should we just return one list(Map) of Requested Entities, instead of two?

**Comment by hinchliff** [comment]
I now have a decent start to some unit tests in the branch [controller_resources_88](https://github.com/RENCI-NRIG/orca5/compare/controller_resources_88).

Any comments on the proposal?

**Comment by ibaldin** [comment]
@hinchliff Sorry, I did look at it, forgot to say something. I think it looks reasonable. When you say 'tests for createSlice()' do you mean tests that address this particular behavior?

**Comment by hinchliff** [comment]
> tests that address this particular behavior?

Not yet.  So far I have only added tests that should pass.  Getting that to work communicating with a "live" SM and AM+Broker (in emulation in Docker) was not that difficult.  Getting it work in a more appropriate unit test manner that did not need to communicate to running servers was more difficult.  These are the two tests that I have currently checked in (and I plan to remove, or at least disable, the 'live' test at a later point).

Now that this mock framework is in place, it should be easier to add additional tests that will expose this particular behavior that we want to change.  (Write a failing test first, then change the code to pass the test.)

**Comment by paul-ruth** [comment]
The proposal from a few messages back seems good (at least from the perspective of the user).  I can't really speak to the lower level details of the proposal.

**Comment by hinchliff** [comment]
Well, we have a problem.  During the createSlice() method, all of the reservations are in the `Invalid` state, meaning that they haven't become either Ticketed or Failed yet.

**Comment by ibaldin** [comment]
Does it mean you are not seeing responses from the Broker?

**Comment by hinchliff** [comment]
Correct, it looks like the Controller returns from the createSlice() method, without waiting for a response from the Broker.

**Comment by ibaldin** [comment]
So the embedding logic asks if resources are available on broker, gets a response, issues tickets based on topology emedding and returns from the call? Is that right? 

If so we may need to look at SM policy, which deals with returned tickets from the broker.

**Comment by hinchliff** [comment]
> So the embedding logic asks if resources are available on broker, gets a response, issues tickets based on topology embedding and returns from the call? Is that right?

I think that is correct.  I will start looking at SM policy -- like `ServiceManagerSimplePolicy` ?

**Comment by ibaldin** [comment]
Config.xml should tell you which policy is configured for the SM, I think.

**Comment by hinchliff** [comment]
It looks like the [processDemand()](https://github.com/RENCI-NRIG/orca5/blob/master/core/policy/src/main/java/orca/policy/core/ServiceManagerSimplePolicy.java#L194) function in `ServiceManagerSimplePolicy` is given a `ReservationSet` of reservations, and these reservations have Slice info, which contains references to all of the reservations in the slice.

So it looks like we could check all of a Slice's reservations in this function, and not demand / fail them if any reservation within that slice is in a Failed state.  (I'll actually check to see if Failures show up this time, before I spend too much time on it :)

Does this sound reasonable?  @ibaldin @YufengXin @paul-ruth ?

**Comment by ibaldin** [comment]
Yes, I think that’s the way to go. And yes on the caveat you added.

**Comment by hinchliff** [comment]
Nope, this won't work either.  All of the reservations are in the `Nascent` state at this point.

**Comment by ibaldin** [comment]
We need to consult with Jeff about this behavior. The redeem mechanism seems to be on auto-pilot, but there should be a policy governing this.

-ilya

**Comment by hinchliff** [comment]
The [redeem()](https://github.com/RENCI-NRIG/orca5/blob/master/core/shirako/src/main/java/orca/shirako/kernel/KernelWrapper.java#L838) function of `KernelWrapper` (or [ServiceManager.processRedeeming()](https://github.com/RENCI-NRIG/orca5/blob/master/core/shirako/src/main/java/orca/shirako/core/ServiceManager.java#L343)) are places we can start to see this, although the SM seems to start redeeming ticketed reservations as soon as they are ticketed -- other reservations in the Slice may still be Nascent.

We probably will need to change the SM to 

1. wait until all reservations in a Slice are all non-nascent (ticketed or failed) before redeeming
1. if any reservations are Failed, then somehow fail/cancel the slice/changes (modify might be tricky)

The place to do this is probably in [checkPending()](https://github.com/RENCI-NRIG/orca5/blob/master/core/policy/src/main/java/orca/policy/core/ServiceManagerCalendarPolicy.java#L69) in `ServiceManagerCalendarPolicy`.  I'm not sure what options we have for notifying the user at this point.

**Comment by ibaldin** [comment]
The user will have to be updated asynchronously, but I think cloning the calendar policy class and creating a new implementation that does what we want on redeem is par for the course.

**Comment by hinchliff** [comment]
I had most of the above commit done before you suggested moving it to a new calendar policy class, but it's still just in the [controller_resources_88](https://github.com/RENCI-NRIG/orca5/compare/controller_resources_88) branch, so it will be easy enough to move if you want to.

I was keeping it in the existing policy file, since we had been talking about changing the default behavior.  But either way is fine.

I'm not sure what else I may need to do for cleanup (of the slice full of failed reservations) or how best to asynchronously notify the user, but this is at least a start.  In my limited testing so far, Flukes doesn't even show the slice in the list of My Slices, so that might be getting cleaned up already.

**Comment by ibaldin** [comment]
I think its best to create a new class and subclass its behavior from the calendar policy. We should then be able to reconfigure the containers to use a different SM control. 

About the user notification - we need to figure out how the controller can hold on to some notion of the slice so it can answer a status query. Not answering or saying the slice is lost isn’t really a good option. We may need to talk about this.

**Comment by ibaldin** [comment]
There's an additional wrinkle on this issue as I'm realizing now. In the controller createSlice() there is a way to delay submitting reservations to SM for the broker that was added to deal with issues related to VLAN tag management in multi-point connections and also OSCARS reliability. Basically it delays any slice from going forward that includes Internet2/ESnet reservations if there is another slice being provisioned. There's a thread that periodically wakes up and checks if the next slice should go forward. 

The relevant code is in SliceDeferThread class in the controller.xmlrpc package. 

I suspect we will need to deal with it separately, perhaps (hopefully) getting rid of that thread altogether now, especially with the expected OSCARS 1.0 migration.

@YufengXin Yufeng - I think this thread also had something to do with multipoint vs. point-to-point inter-domain reservations and tag syncing?

**Comment by hinchliff** [comment]
Updates from this morning's meeting:

1. Don't need to do anything with SliceDeferThread, for this ticket.
1. User will be required to ask for Slice status.  Controller should provide user with information to query on.  The [proposal above](https://github.com/RENCI-NRIG/orca5/issues/88#issuecomment-272277819) with information on TicketRequestEntities should be sufficient. This was already added to createSlice(), and can be added to modifySlice().
1. Right now I fail the tickets in the SM, but I need to tell the Broker that they are cancelled.
1. I need to track down why a new Slice with failed reservations is disappearing so quickly.  There may be a bug in closeDeadSlice() or XmlrpcControllerSlice.reevaluate()
1. I need to update the new ServiceManagerCalendarPolicy.checkPending() to better handle modifySlice() cases:
   1. New calls to modifySlice() should not fail because of previous modifySlice() failures.  Might need to add state to slice to track which action created each reservation.
   1. Reservations should not fail if they are in a different site from a failed reservation.

**Comment by hinchliff** [comment]
Does [this method of getting the Site from a Reservation](https://github.com/RENCI-NRIG/orca5/blob/controller_resources_88/core/policy/src/main/java/orca/policy/core/ServiceManagerTicketReviewPolicy.java#L159) look like it will work across all sites?

Using Authority Name would have been better than ResourceType, but unfortunately Failed reservations don't contain an Authority Name.  (Unless we decide to change that).  I haven't found any better field to look at in the Reservation.

Also ... I had meant to ask if the new policy name of `ServiceManagerTicketReviewPolicy` sounded reasonable?  Any other suggestions?
