### ISSUE TITLE
Make configurable the number of threads run by Jetty to allow servicing multiple concurrent user and JMX requests

### ISSUE THREAD

**Issue by ibaldin** [RENCI-NRIG/orca5#89]
Issue: need to increase the number of threads to make sure JMX and user requests are serviced in a timely fashion. (per @vjorlikowski )

Solution:

Controller: has a default of 10 threads and a property called xmlrpc.controller.threads that can override this default. Requires a stateful restart to take effect. 

Actor container: the number of threads is hardcoded to 2 (orca.server.OrcaServer). Needs code change to be a property
```
		SelectChannelConnector connector = new SelectChannelConnector();
		connector.setPort(ServerPort);
		connector.setAcceptors(2);
		server.addConnector(connector);
```
@hinchliff - Alan, can you modify the code to supply the number of threads via property in orca.properties (something like container.threads or similar) 
@mcevik0 - Mert can redeploy the code probably after we also fix #36 and #88

**Comment by hinchliff** [comment]
Starting looking at this.   It looks like the Controller has a setting for the number of threads for SSL connections at [line 142](https://github.com/RENCI-NRIG/orca5/blob/master/controllers/xmlrpc/src/main/java/orca/controllers/xmlrpc/XmlRpcController.java#L142), but it actually has the same `setAcceptors(2)` for the non-SSL connection just a little earlier at [line 131](https://github.com/RENCI-NRIG/orca5/blob/master/controllers/xmlrpc/src/main/java/orca/controllers/xmlrpc/XmlRpcController.java#L131) (interestingly under the comment [disable the non-ssl connector](https://github.com/RENCI-NRIG/orca5/blob/master/controllers/xmlrpc/src/main/java/orca/controllers/xmlrpc/XmlRpcController.java#L128)).

In Actors / OrcaServer, there is only a `setAcceptors` for the non-SSL connections at [line 133](https://github.com/RENCI-NRIG/orca5/blob/master/server/src/main/java/orca/server/OrcaServer.java#L133).  The SSL connection [doesn't set this value](https://github.com/RENCI-NRIG/orca5/blob/master/server/src/main/java/orca/server/OrcaServer.java#L166), so presumably it is using a default value of 1.

Do our connections normally use SSL?  So I should add a property like `container.threads` to set that value?  

Should I completely ignore the non-SSL connection?  Are they being somehow disabled by the present code, as hinted at in the Controller?  Or is there anything extra I should do here?

**Comment by ibaldin** [comment]
On controller yes, we use SSL only. Controller rejects connections not coming from SSL-enabled clients. 

We should remove non-SSL connections on the controller altogether. 

On ORCA containers SSL is not used.

**Comment by ibaldin** [comment]
@hinchliff Alan, is this done and ready to deploy? are you waiting for review?

**Comment by hinchliff** [comment]
@ibaldin this is done.  Committed to master.  The property is `container.threads`.

**Comment by hinchliff** [comment]
Release [5.0.3](https://github.com/RENCI-NRIG/orca5/releases/tag/orca-5.0.3) contains this fix.
